<style>
    .footer-height{
        height: 20px;
    }
    </style>
<!--
<div class="content-iframe">
    <div id="chat_div"></div>
    <div id="login_div" style="width: 310px">
        <div id="barrita_chat" style="display: inline;right: 0;">
            <div class="titulo_chat">¿Tienes dudas? ¡consultanos!</div>
            <div class="chat_contentbuttons">
                <div class="chat_minimizer" title='minimizar chat'>
                    <a href="javascript:void(0)" ></a>
                </div>
            </div>
        </div>
        <div id="content_user" style="right: 0;width: 310px;display: none">
            <div class="chat_tittle">
                <div class="titulo_chat">¿Tienes dudas? ¡consultanos!</div>
                <div class="chat_contentbuttons">
                    <div class="chat_minimizer" title='minimizar chat'>
                        <a href="javascript:void(0)" ></a>
                    </div>
                </div>
            </div>
            <div class="content_login">
                <div class="chat_welcome">¡Bienvenido a nuestro chat de valeplaza Antes de iniciar, por favor indique su nombre.</div>
                <form id="chat_user_form" onSubmit="Chat.userReg('admin');return false">
                    <div>
                        <input class="chat_textname" type="text" id="name_chat" name="name_chat" value="" placeholder="Escribe tu nombre y presiona ENTER"/>
                    </div>
                </form>
            </div>
        </div>
        <input type="hidden" id="sessId" name="sessId" value="<?php echo $this->sessId; ?>" />
        <input type="hidden" id="Hilo" name="Hilo" value="<?php echo $this->sessId; ?>" />
    </div>
</div>   -->
<style type="text/css">
.containerwx a{
color:#ffffff !important;}
</style>
<footer class="footer-color containerwx2" id="containerwx">
    <!--<img src="<?php// echo Cit_Server::getContent()->host; ?>logo-footer/footerfp.jpg" class="imgfooterp">-->    
<div class="modul6">
    <div class="footer-cont"> 
            <div class="footer-tipo">
                <div class="float-l">
                    <div class="footer-subtitu">
                        <span>Preguntas frecuentes:</span>
                    </div> 
                    <div class="preg-frec">
                        <a href="http://ayuda.valeplaza.com/viewtopic.php?f=11&t=25" target="_blank"><span>¿Qué es Valeplaza?</span></a>
                    </div>
                    <div class="preg-frec">
                        <a href="http://ayuda.valeplaza.com/viewtopic.php?f=12&t=32" target="_blank"><span>¿Qué son los puntos?</span></a>
                    </div>
                    <div class="preg-frec">
                        <a href="http://ayuda.valeplaza.com/viewtopic.php?f=12&t=33" target="_blank"><span>¿Cómo consigo los puntos?</span></a>
                    </div>
                    <div class="preg-frec">
                        <a href="http://ayuda.valeplaza.com/viewtopic.php?f=13&t=28" target="_blank"><span>¿Qué son los vales?</span></a>
                    </div>
                    <div class="preg-frec">
                        <a href="http://ayuda.valeplaza.com/viewtopic.php?f=13&t=30" target="_blank"><span>¿Cómo canjeo un vale?</span></a>
                    </div>
                </div>
            </div>
            <div class="footer-tipo">
                <div class="float-l">
                    <div class="footer-titu">
                        <span>Tienda</span>
                    </div> 
                    <div class="footer-subtitu sn-foo">
                        <span>Forma parte de nuestra comunidad </span>
                    </div>
                    <div class="footer-info sn-foo">
                        <span>Cada vez son más negocios que se registran en nuestra red y que ahora disfrutan de sus beneficios. Registrate en nuestro <a href="<?php echo Cit_Server::getContent()->host; ?>planes"><b class="hov-subr">Plan Básico</b></a>, es GRATIS, y solo pagas si vendes.</span>
                    </div>
                    <div class="footer-info sn-foo">
                        <div class="float-l"><span>en la fase GRATUITA por tiempo limitado.</span></div>
                        <a href="<?php echo Cit_Server::getContent()->host ?>planes">
                        <div class="btn-footer-reg-aqui float-l">Regístrate aquí</div>
                        </a>
                    </div> 
                    <br>
                    <div class="footer-info float-l sn-foo">
                        <span>Si quieres publicitar con nosotros comunícate con <span class="color-bl">publicidad@valeplaza.com</span></span>
                    </div> 
                </div>
            </div>
           <!-- <div class="footer-tipo">
                <div class="float-l">
                    <div class="footer-titu">
                        <span>Agente VP</span>
                    </div> 
                    <div class="footer-info sn-foo">
                        <span>Se parte de nuestro equipo de Agentes VP y mejora tus ingresos</span>
                    </div>
                    <div class="footer-info sn-foo">
                        <span>trabajando de forma independiente. Logra tus objetivos y goza de</span>
                    </div>
                    <div class="footer-info sn-foo">
                        <span>nuestros beneficios.</span>
                    </div> 
                    <div class="footer-info sn-foo">
                        <span>Infórmate más a detalle sobre nuestro<a href="https://issuu.com/valeplaza/docs/plan_de_ex__to_agentes_vp" target="_blank"><span class="color-bl"> Plan de Éxito</span></a> y empieza a</span>
                    </div>
                    <div class="footer-info sn-foo">
                        <span>vivir mejor..</span>
                    </div> 
                    <br>
                    <div class="footer-info sn-foo">
                        <span>Si tienes alguna consulta escríbenos a agentevp@valeplaza.com</span>
                    </div>               
                </div>
            </div>-->
        <div class="footer-tipo">
            <div class="footer-titu">
                <span>Descarga nuestra APP.</span>
           </div> 
            <div class="cont-img-app">
                <div class="btn-app">
                     <img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/googleplay.png" >
                </div>
                <div class="btn-app">
                     <img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/apple.png" >
                </div>
            </div>
            <!--<div class="footer-subtitu float-l">
                <span>Suscríbete y conoce nuestras novedades</span>
           </div>
            <div class="div-suscribirse">
                <input class="input-suscribir" type="text" placeholder="Ingresa tu correo">
                <div class="img-suscribe">
                    <img src="<?php// echo Cit_Server::getContent()->host; ?>logo-footer/mensaje.png" >
                </div>
            </div>-->
        </div>
    </div>
    <div class="footer-cont border-bottom">
        <div class="footer-tipo footer-height">
           
        </div>
        <div class="footer-tipo footer-height">
            
        </div>
        <div class="footer-tipo">
            <div class="float-l">
             <!--   <div class="img-age">
                    <img src="<?php// echo Cit_Server::getContent()->host; ?>logo-footer/icon-agente.png" >
                </div>
                <div class="titu-reg-age">
                    <span>¿AÚN NO ERES AGENTE EN VP?</span>
                </div>
                <div class="go-reg-age">
                    <span>Si ya estas registrado como usuario, envianos tu cv</span>
                </div>
                <div class="cont-btn-age-aqui">
                    <div class="btn-age-aqui">
                          <img data-toggle="modal" data-target="#AgentesForm" src="<?php// echo Cit_Server::getContent()->host; ?>logo-footer/botonage.png">
                    </div>
                </div>-->
                <div class="cont-redes-sociales">
                    <div class="redes-sociales">
                        <div class="logo-red-social">
                            <a href="https://www.instagram.com/valeplazaperu/" target="_blank"><img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/instagram.png" > </a>
                        </div>
                        <div class="logo-red-social">
                            <a href="https://www.facebook.com/ValeplazaPeru/" target="_blank"><img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/fb.png" > </a>
                        </div>
                        <div class="logo-red-social">
                            <a href="https://www.twitter.com/@VPValeplaza" target="_blank"><img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/twitter.png" > </a>
                        </div>
                        <div class="logo-red-social logoyt">
                            <a href="https://www.youtube.com/channel/UCt6i0NHyV4_W5zO_hsCIHFw" target="_blank"><img src="<?php echo Cit_Server::getContent()->host; ?>logo-footer/youtube.png" > </a>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
    <div class="politicas-cont">
        <div class="div-derechos">
            <span>2017 Valeplaza Derechos reservados</span>
        </div>
        <div class="div-derechos float-r">
            <div class="nom-menu-footer">
                <a href="http://ayuda.valeplaza.com/viewtopic.php?f=11&t=25" target="_blank"><span>Nosotros</span></a>
            </div>
            <div class="nom-menu-footer">
                <a href="http://ayuda.valeplaza.com/" target="_blank"><span>Ayuda</span></a>
            </div>
            <div class="nom-menu-footer">
                <a href="<?php echo Cit_Server::getContent()->host.'condiciones'; ?>" target="_blank"><span>Términos y condiciones</span></a>
            </div>
            <div class="nom-menu-footer">
                <a href="<?php echo Cit_Server::getContent()->host.'privacidad'; ?>" target="_blank"><span>Políticas de privacidad</span></a>
            </div>
            <div class="nom-menu-footer noborder">
                <a href="mailto:contacto@valeplaza.com" target="_blank"><span>Contacto</span></a>
            </div>
        </div>
    </div>
</div> 
    <div class="modal fade" id="AgentesForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog-landing">
<div class="modal-content-landing">
    <!--<img class="img-fondop1"src="<?php// echo Cit_Server::getContent()->host; ?>login-iconos/fondo.jpg">-->
    <div class="vp-titu">
        <img class="vp-img-titu"src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/headervp.png">
    </div>
<div class="modal-body-landing">
    <div class="modal-login-landing-left">
        <div class="modal-login-titulo-landing titulo2">
            <div class="titu-iniciarsesion">
                <span class="enuevo">INICIAR SESIÓN</span>
                <p class="sug-usu-vp">(Para ingresar deberás estar registrado</p>
                <p class="sug-usu-vp">como usuario en Valeplaza)</p></div>
        </div> 
        <form method="post" id="frm-registro-agente">
            <div class="modal-input-landing"><div class="color-input"><input placeholder="Correo electrónico" class="modal-input-text logo1" type="text" id="agente_correo"></div></div>   
            <div class="modal-input-landing"><div class="color-input"><input placeholder="Contraseña" class="modal-input-text logo2" type="password" id="agente_pass"></div></div>
        <div class="modal-input-recordar"><input type="checkbox" name="recordarme" <?php if(!empty($this->vp_recordar)) echo "checked='checked'"; ?> id="agente_recordarme" class="left">
            <p class="record">Recordarme</p></div>
            <div class="modal-input-ingresar"><input type="submit" class="btn-empiezaya" value=""></div>
        </form>
        <div class="modal-olvidaste">
            <a href="<?php echo Cit_Server::getContent()->host."recuperar-password"?>"><p class="obten-ayuda">¿Has olvidado tu información de Inicio de sesión?</p></a>
            <a href="<?php echo Cit_Server::getContent()->host."recuperar-password"?>"><p class="obten-ayuda">Obtén ayuda</p></a>
        </div>
        <div class="modal-olvidaste">
            <p>
            <div>
                <img src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/linea.png">
            </div>
            <p>
        </div>
        <div class="con-fb" id="a_login_fb_agente"><div class="img-vi"><img src="<?php echo Cit_Server::getContent()->host; ?>login-iconos/fb.jpg"></div><div class="sessionfb">Iniciar sesión con Facebook</div></div>
    </div>    
<div class="modal-login-landing-right">
        <div class="modal-login-titulo-landing titulo3">
            <p class="enuevo2">REGÍSTRATE</p>
            <p class="enuevo2">COMO USUARIO</p></div>
        <form method="post" id="form-reg-cliage">
            <div class="modal-input-landing"><div class="color-input"><input placeholder="Nombre" class="modal-input-text logo3" type="text" id="nom_usu_age" name="nom_usu_age"></div></div>
            <div class="modal-input-landing"><div class="color-input"><input placeholder="Apellido" class="modal-input-text logo4" type="text" id="ape_usu_age" name="ape_usu_age"></div></div>
            <div class="modal-input-landing"><div class="color-input"><input placeholder="Correo electrónico" class="modal-input-text logo5" type="email" id="email_usu_age" name="email_usu_age"></div></div>
            <div class="modal-input-landing">
              <div class="color-input">  <select class="modal-input-select logo6" id="slpaisagente" name="slpaisagente">
                    <option value="">Selecciona tu país</option>
                    <?php if(!empty($this->paises)):?>
                    <?php foreach($this->paises as $value):?>
                    <option value="<?php echo $value['pais_id']?>"><?php echo $value['pais_nombre']?></option>
                    <?php endforeach;?>
                    <?php endif;?>
                  </select></div></div>
            <div class="modal-input-landing">
             <div class="color-input">  <select  class="modal-input-select logo7" id="slciudadagente" name="slciudadagente">
                <option value="">Seleccionar ciudad</option>
                </select>
             </div></div>
            <div class="modal-input-ingresar"><input type="hidden" id="h_fb_agente"/><input type="submit" class="btn-reg-ti" value=""></div>
          <!--  <img class="reg-emp"src="<?php// echo Cit_Server::getContent()->host; ?>img-slider/registrateyafp.png" id="h_fb">    -->         
        </form>
        <div class="modal-olvidaste"><span>Accediendo acepto los términos y condiciones y las</span><br>   <a href="<?php echo Cit_Server::getContent()->host.'privacidad'; ?>" target="_blank">Políticas de privacidad</a></div>   
    </div>
    <div class="cont-reg-tiend">
        <div class="reg-tie-cent">
        <div class="img-tienda-car">
            <img src="<?php echo Cit_Server::getContent()->host; ?>login-iconos/tienda.png">
        </div>
        <div class="text-reg-tie">
            <a href="<?php echo Cit_Server::getContent()->host ?>planes">
            <span>REGÍSTRATE COMO TIENDA AQUÍ</span>
            </a>
        </div>
        </div>
    </div>
</div>
</div>
<!-- /.modal-content --> 
</div>
<!-- /.modal-dialog --> 
</div>
 <!--   
<div class="content-iframe">
<div id="chat_div"></div>
<div id="login_div" style="width: 310px">
<div id="barrita_chat" style="display: inline;right: 0;">
<div class="titulo_chat">¿Tienes dudas? ¡consultanos!</div>
<div class="chat_contentbuttons">
<div class="chat_minimizer" title='minimizar chat'>
<a href="javascript:void(0)" ></a>
</div>
 </div>
</div>
<div id="content_user" style="right: 0;width: 310px;display: none">
<div class="chat_tittle">
<div class="titulo_chat">¿Tienes dudas? ¡consultanos!</div>
<div class="chat_contentbuttons">
<div class="chat_minimizer" title='minimizar chat'>
<a href="javascript:void(0)" ></a>
 </div>
</div>
</div>
<div class="content_login">
<div class="chat_welcome">¡Bienvenido a nuestro chat de valeplaza Antes de iniciar, por favor indique su nombre completo  o nombre de la empresa.</div>
<form id="chat_user_form" onSubmit="Chat.userReg('admin');return false">
<div>
<input class="chat_textname" type="text" id="name_chat" name="name_chat" value="" placeholder="Escribe tu nombre y presiona ENTER"/>
</div>
</form>
</div>
</div>
<input type="hidden" id="sessId" name="sessId" value="<?php// echo $this->sessId; ?>" />
<input type="hidden" id="Hilo" name="Hilo" value="<?php// echo $this->sessId; ?>" />
</div>
</div> -->   
</footer>
<script>
/*$(document).ready(function(){
if($.cookie('name_chat')){
$("#login_div").hide();
}else{
$("#login_div").show();
}})*/
</script>