
<script>
  /*(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-55157062-1', 'auto');
  ga('send', 'pageview');*/
</script>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1652248801673567&version=v2.2";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
</script>
<script>
var fb = {
    config :{
        app_id : <?php echo Zend_Registry::get('config')->facebook->appId; ?>, 
        use_xfbml : true,
        extendPermissions : 'public_profile,email,user_friends,publish_actions',
        locale : 'es_ES'
    },
    perms : [],
    hasPerm : function (perm) { for(var i=0, l=fb.perms.length; i<l; i++) { if(fb.perms[i] == perm) {return true;}} return false; },
    logged : false,
    user : false, // when login, is a user object: http://developers.facebook.com/docs/reference/api/user
    login : function (callback){
        FB.login(function(r) {
            //alert("entroooo")
            if (r.status == 'connected') {
                //alert("conectado")
                FB.api('/me/permissions',function(perm){
                    fb.logged = true;
                    fb.perms = [];
                    for(i in perm.data[0]){
                        if (perm.data[0][i] == 1){
                            fb.perms.push(i);
                        }
                    }
                });    
                fb.getUser(callback);
            } else {
                //alert("no conectado")
                fb.logged = false;
                fb.perms = [];
                callback();
            }
        },{scope:fb.config.extendPermissions});
        return false;
    },
    syncLogin : function (callback){
        if (!callback) callback = function(){};
        FB.getLoginStatus(function(r) {
            if (r.status == 'connected' ) {
                FB.api('/me/permissions',function(perm){
                    fb.logged = true;
                    fb.perms = [];
                    for(i in perm.data[0]){
                        if (perm.data[0][i] == 1){
                            fb.perms.push(i);
                        }
                    }
                });    
                fb.getUser(callback);
                return true;
            } else {
                fb.logged = false;
                callback();
                return false;
            }
        });
    },
    logout : function(callback) {FB.logout(callback);},
    getUser : function(callback){
        //alert("entro")
        FB.api('/me?fields=id,name,email,last_name,first_name',function(r){
            var user = r;
            /*alert(r.name);
            alert(r.first_name);
            alert(r.last_name);
            alert(r.email);*/
            user.picture = "https://graph.facebook.com/"+user.id+"/picture?type=large";
            fb.user=user; callback(user); 
        }); 
    },
    getFriends : function(callback){
        FB.api('/me/friends', function(r){
            callback( r.data );
        })
    },
    share : function(u_share, width_height){
        window.open('https://www.facebook.com/sharer/sharer.php?u='+u_share, 'facebook-share-dialog', width_height);
    },
    sendMessage : function(to, username, requestCallback){
        FB.ui({
            method:'send',
            to: to,
            link: 'https://www.valeplaza.com/perfil/'+username
        }, requestCallback );
    },
    publish : function (publishObj,callback,noReTry) {
        // publishObj: http://developers.facebook.com/docs/reference/api/post   
        if (fb.logged){
            FB.ui({
                method: 'share_open_graph',
                action_type: 'og.likes',
                action_properties: JSON.stringify({
                    object:publishObj
                })
                }, function(response){
                        if (!response || response.error) {
                            callback(false);
                        } else {
                            callback(true);
                        }
                });
        }else{
            if (!noReTry)
                return fb.login(function() { 
                    return fb.publish(publishObj,callback,1)
                });
            else{
                callback(false);
                return false;
            }
        }
    },
    inviteFriends : function ( requestCallback){
        FB.ui({ 
            method: 'apprequests',
            message: 'Te invito a Life!'
        }, requestCallback );
    },
    readyFuncs : [],
    ready: function(func){fb.readyFuncs.push(func)},
    launchReadyFuncs : function () {for(var i=0,l=fb.readyFuncs.length;i<l;i++){fb.readyFuncs[i]();};}
}

function requestCallback2222(response){
    console.log(response, 'true');
    if(response){
        return true;
    }else{
        return false;
    }
}

window.fbAsyncInit = function() { 
  if (fb.config.app_id) FB.init({appId: fb.config.app_id, status: true, cookie: true, xfbml: fb.config.use_xfbml,version: 'v2.2'});
  fb.syncLogin(fb.launchReadyFuncs);
};

/*(function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/all.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));*/
/*(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1652248801673567&version=v2.2";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));*/
/*************************************************************/
</script>

    


<script>


$(document).ready(function(){
    $('#a_login_fb').on('click', function(){
        if(fb.logged){
            //alert(fb.user)
            $.ajax({
                type: 'post',
                url: '<?php echo Cit_Server::getContent()->host; ?>outh/loginfacebook',
                data:{
                'email_usu':fb.user.email,
                'nom_usu':fb.user.first_name,
                'ape_usu':fb.user.last_name,
                'id':fb.user.id
                },
                beforeSend:function(objeto){
                    $('#bloquea').css("display",'block');
                },
                success: function(json) {
                    $('#bloquea').css("display",'none');
                    responce = jQuery.isEmptyObject($.trim(json))
                        if(responce)
                        {
                            document.location.href="<?php echo Cit_Server::getContent()->host.$this->urlRedirect; ?>"
                        }else{
                            result=jQuery.parseJSON(json);
                            var response =  jQuery.parseJSON(json);
                            $(response).each(function(k, v){
                                cad=v.error
                                if(v.error=="error"){
                                    bootbox.alert("Error de conexion");
                                }else{
                                    $("#nom_usu").val(fb.user.first_name);
                                    $("#ape_usu").val(fb.user.last_name);
                                    $("#email_usu").val(fb.user.email);
                                    $("#h_fb").val(fb.user.id);
                                }
                            })
                        }
                }
            });            
            return false;
        }else{
            fb.login(function(){
                if(fb.logged){
                    //alert(fb.user.email)
                    $.ajax({
                        type: 'post',
                        url: '<?php echo Cit_Server::getContent()->host; ?>outh/loginfacebook',
                        data:{
                            'email_usu':fb.user.email,
                            'nom_usu':fb.user.first_name,
                            'ape_usu':fb.user.last_name,
                            'id':fb.user.id
                        },
                        beforeSend:function(objeto){
                            $('#bloquea').css("display",'block');
                        },
                        success: function(json) {
                            $('#bloquea').css("display",'none');
                            responce = jQuery.isEmptyObject($.trim(json))
                                if(responce)
                                {
                                    document.location.href="<?php echo Cit_Server::getContent()->host.$this->urlRedirect; ?>"
                                }else{
                                    result=jQuery.parseJSON(json);
                                    var response =  jQuery.parseJSON(json);
                                    $(response).each(function(k, v){
                                        //cad=v.error
                                        if(v.error=="error"){
                                            bootbox.alert("Error de conexion");
                                        }else{
                                            $("#nom_usu").val(fb.user.first_name);
                                            $("#ape_usu").val(fb.user.last_name);
                                            $("#email_usu").val(fb.user.email);
                                            $("#h_fb").val(fb.user.id);
                                        }
                                    })
                                    
                                    
                                }
                        }
                    });        
                    return false;
                }
            });
        }
    });
    $('.header-menu a').hover(
       function(){ $(this).addClass('mov-menua') },
       function(){ $(this).removeClass('mov-menua') }
    );
}) ; 

</script>
<style type="text/css">

.dropdown-menu {
    position: absolute;
    top: 0px;
    left: 33px !important;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 116px;
    padding: 5px 0 0px 0px;
    margin: 30px 0 0 !important;
    font-size: 14px;
    list-style: none;
    background-color: #ffffff;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
}
</style>

    <link href="../css/flags.css" rel="stylesheet">
   
<header id="header" role="banner">
<div class="header-landing-container ">
<div class="header-landing-logo">
 <a href="/"></a> 
</div>
    <div class="header-menu">
        <a id="menua" href="<?php echo Cit_Server::getContent()->host ?>empresas">Empresas</a>
        <a id="menua" data-toggle="modal" data-target="#IniciarSesion2" href="#">Registro del usuario</a>
        <a id="menua" data-toggle="modal" data-target="#IniciarSesion" href="#">Login</a>
    </div> 
    <div class="header-logo">
        <a href="https://www.facebook.com/ValeplazaPeru/"  target="_blank">
        <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/face.png">
        </a>
        <a href="https://www.twitter.com/@VPValeplaza"  target="_blank">
        <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/twi.png"> 
        </a>
        <a href="https://www.instagram.com/valeplazaperu/"  target="_blank">
        <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/insta.png"> 
        </a>
      <!--  <a href="whatsapp://send?text=973958780" data-action="share/whatsapp/share">-->
        <img src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/what.png"> 
       <!-- </a>-->
        <span class="tx-what">Whatsapp:</span>
        <span class="tx-whatnum">973958780</span>
    </div>
   <!-- <div id="content-pais" style="float: right;width: 168px;height: 40px;padding: 5px;">
        <div id='basic' data-input-name='country' data-selected-country='PE'></div>
    </div>-->

</div>

</header>
<div class="modal fade" id="IniciarSesion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-content-log">
            
            <div class="cont-log-mdl">
                <div class="fil-log-mdl">
                    <img class="fon-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/img2.jpg">
                    <div class="tx-fon-log">
                        <p class="tx-fon-1" ><span class="rou-bld">BIENVENIDO</span><span>.</span></p>
                        <p class="tx-fon-2">Empieza a disfrutar y a vivir una nueva experiencia en la Red Valeplaza.</p>
                    </div>
                </div>
                <div class="fil-log-mdl">
                    <div class="cont-fil-log-mdl">
                        <form method="post" id="frm-registro">
                        <p class="titu-log-mdl">Iniciar Sesión</p>
                        <p class="tx-ing-log">Para ingresar deberás estar registrado como usuario en Valeplaza</p>
                        <div class="cont-inpt-log-mdl">
                            <input id="header_correo"  class="inpt-log-mdl" type="text" placeholder="Correo electrónico" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input id="header_pass" class="inpt-log-mdl" type="password" placeholder="Contraseña" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input type="checkbox" name="recordarme" <?php if(!empty($this->vp_recordar)) echo "checked='checked'"; ?> id="recordarme" class="left">
                            <p class="record">Recordarme</p>
                        </div>
                        <input type="submit" class="btn-ing" value="Ingresar">
                        <div class="modal-term-log">
                            <a href="<?php echo Cit_Server::getContent()->host."recuperar-password"?>"><span class="hov">Recordar <b>CONTRASEÑA</b></span></a>
                           <p class="obten-ayuda">¿Aún no tienes cuenta? <b id="modal_session_tienda" class="hov-subr cpon">REGÍSTRATE AQUÍ</b></p>
                        </div>
                        <div>
                            <img class="linea-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/linea.png">
                        </div> 
                         <div class="cont-fb-log" id="a_login_fb"><img src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/btnfb.png"></div>
                    </form>
                    </div>
                </div>
            </div>
        </div>

<!-- /.modal-dialog --> 
</div>
    <div class="modal fade" id="IniciarSesion2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-content-log">
            
            <div class="cont-log-mdl">
                <div class="fil-log-mdl">
                    <img class="fon-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/img1.jpg">
                    <div class="tx-fon-log">
                        <p class="tx-fon-1" ><span class="rou-bld">BIENVENIDO</span><span>.</span></p>
                        <p class="tx-fon-2">Empieza a disfrutar y a vivir una nueva experiencia en la Red Valeplaza.</p>
                    </div>
                </div>
                <div class="fil-log-mdl">
                    <div class="cont-fil-log-mdl">
                        <form method="post" id="form-reg-cli">
                        <p class="titu-log-mdl">Regístrate</p>
                        <div class="cont-inpt-log-mdl">
                            <input id="nom_usu" name="nom_usu" class="inpt-log-mdl" type="text" placeholder="Nombre" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input id="ape_usu" name="ape_usu" class="inpt-log-mdl" type="text" placeholder="Apellido" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input type="email" id="email_usu" name="email_usu" class="inpt-log-mdl" placeholder="Correo electrónico" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <select id="slpais" name="slpais" class="inpt-log-mdl selec-log">
                                <option value="">Selecciona tu pais</option>
                                <?php if(!empty($this->paises)):?>
                                <?php foreach($this->paises as $value):?>
                                <option value="<?php echo $value['pais_id']?>"><?php echo $value['pais_nombre']?></option>
                                <?php endforeach;?>
                                <?php endif;?>
                            </select>
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <select id="slciudad" name="slciudad" class="inpt-log-mdl selec-log">
                                <option value="">Selecciona tu ciudad</option>
                            </select>
                        </div>
                        <input type="hidden" id="h_fb"/>
                        <input type="submit" class="btn-ing" value="Ingresar">
                        <div class="modal-term-log">
                            <span>Accediendo acepto los términos y condiciones y las</span>
                            <br>
                            <a href="<?php echo Cit_Server::getContent()->host.'privacidad'; ?>" target="_blank"><b class="hov">Políticas de privacidad</b></a>
                        </div>
                        <a href="<?php echo Cit_Server::getContent()->host ?>planes">
                        <div class="btn-reg-log-tie">Regístrate como tienda aquí</div>
                        </a>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <script src="../js/jquery.flagstrap.js"></script>

<script>
    
    

    /*$('#options').flagStrap({
        countries: {
            "AU": "Australia",
            "GB": "United Kingdom",
            "US": "United States"
        },
        buttonSize: "btn-sm",
        buttonType: "btn-info",
        labelMargin: "10px",
        scrollable: false,
        scrollableHeight: "350px"
    });

    $('#advanced').flagStrap({
        buttonSize: "btn-lg",
        buttonType: "btn-primary",
        labelMargin: "20px",
        scrollable: false,
        scrollableHeight: "350px"
    });*/
    </script>
<script>
/*$('#a_conect_fb').on('click', function(){
    if(fb.logged){
        $("#nom_usu").val(fb.user.first_name);
        $("#ape_usu").val(fb.user.last_name);
        $("#email_usu").val(fb.user.email);
    }else{
        fb.login(function(){
            if(fb.logged){
                $("#nom_usu").val(fb.user.first_name);
                $("#ape_usu").val(fb.user.last_name);
                $("#email_usu").val(fb.user.email);
            }
        });
    }
});*/
$("#slpais").change(function(){
    $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>index/getprovi',
            data:{
                    'pais': $("#slpais").val()
                },
            success: function(json) {
                    $("#slciudad").empty();
                    $("#slciudad").append("<option value=''>Selecciona tu ciudad</option>")
                        result=jQuery.parseJSON(json);
                        $(result).each(function(k, v){
                            $("#slciudad").append("<option value='"+v.prov_id+"'>"+v.prov_nombre+"</option>")
                        });         
                }
        })
});
$("#modal_session_tienda").click(function(){
    $("#IniciarSesion").modal("hide");
    $("#IniciarSesion2").modal("show");
})

$('#frm-registro').validate({
    rules:{
        header_pass : {    
            required : true //para validar campo vacio
        },
        header_correo : {    
            required : true,
            email:true//para validar campo vacio
        }
    },
    messages:{
        header_pass : {    
            required : 'Falta indicar el password' //para validar campo vacio
        },
        header_correo : {  
            required    : "Falta indicar su correo electrónico",
            email  : "Ingrese un formato correcto de correo"//para validar formato email
        }
    }, 
    highlight: function(element) {
        $(element).addClass('errorborde');
    }, 
    unhighlight: function(element) {
        $(element).removeClass('errorborde');
    },
    submitHandler: function(form) {
        if($("#recordarme").is(":checked")){
            rec=1;
        }else{
            rec=0
        }
        $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>outh/login',
            data:{
                'password':$("#header_pass").val(),
                'email':$("#header_correo").val(),
                'rec':rec
            },
            beforeSend:function(objeto){
                $('#bloquea').css("display",'block');
            },
            success: function(json) {
                $('#bloquea').css("display",'none');
                var response =  jQuery.parseJSON(json);
                //alert(response.nick)
                    responce = jQuery.isEmptyObject($.trim(response.nick))
                    if(responce){
                         cad="";
                        $(response.mensajes).each(function(k, v){
                            cad=v.mail
                        })
                        bootbox.alert(cad);
                    }else{
                        //document.location.href="<?php //echo Cit_Server::getContent()->host; ?>"+"perfil/"+response.nick
                        document.location.href="<?php echo Cit_Server::getContent()->host.$this->urlRedirect; ?>";
                       
                    }
                }
        });        
        return false;                                
    }                        
});

$('#form-reg-cli').validate({
    rules:{
        nom_usu : {    
            required : true //para validar campo vacio
        },
        ape_usu : {    
            required : true //para validar campo vacio
        },
        email_usu : {    
            required : true,
            email:true//para validar campo vacio
        },
        slpais : {    
            required : true //para validar campo vacio
        },
        slciudad : {    
            required : true //para validar campo vacio
        }
    },
    messages:{
        nom_usu : {    
        //para validar campo vacio
            required    : "Falta indicar su nombre"  //para validar formato email
        },
        ape_usu : {    
        //para validar campo vacio
            required    : "Falta indicar su apellido"  //para validar formato email
        },
        email_usu : {    
        //para validar campo vacio
            required    : "Falta su correo electrónico",
            email  : "Ingrese un formato correcto de correo"//para validar formato email
        },
        slpais : {    
        //para validar campo vacio
            required    : "Falta indicar su país"  //para validar formato email
        },
        slciudad : {    
        //para validar campo vacio
            required    : "Falta indicar su ciudad"  //para validar formato email
        }
    }, 
    highlight: function(element) {
        $(element).addClass('errorborde');
    }, 
    unhighlight: function(element) {
        $(element).removeClass('errorborde');
    },
    submitHandler: function(form) {
        $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>outh/regintriga',
            data:{
            'nom_usu':$("#nom_usu").val(),
            'ape_usu':$("#ape_usu").val(),
            'email_usu':$("#email_usu").val(),
            'pais':$("#slpais").val(),
            'ciudad':$("#slciudad").val(),
            'fb':$("#h_fb").val()
            },
            beforeSend:function(objeto){
            $('#bloquea').css("display",'block');
            },    
            success: function(json) {
                $('#bloquea').css("display",'none');
                responce = jQuery.isEmptyObject($.trim(json))
                if(responce){
                    bootbox.alert("Gracias por registrarse, se ha unido al futuro de las ofertas online. Se le ha enviado un correo para que confirme su registro",function(){
                        document.location.href="<?php echo Cit_Server::getContent()->host?>espera"
                    })
                }else{
                    var response =  jQuery.parseJSON(json);
                    cad="";
                    $(response).each(function(k, v){
                        cad=v.mail_status
                    })
                    bootbox.alert(cad);
                }
            }
        });        
        return false;
    }                  
});
</script>

<script>
    /*$(document).ready(function() {
        
    $( "#content-pais" ).on( "change", "#flagstrap", function() {
        document.location.href="<?php //echo Cit_Server::getContent()->host."?code=" ?>"+$("#flagstrap").val();
      });
    })*/
</script>