
<link href="<?php echo Cit_Server::getContent()->host; ?>css/stilos.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet"  >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/Bienvenido.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/bootstrap.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/bootstrap-datetimepicker.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/Estructurando.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/clientes.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/tienda.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/style.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/jquery.ui.chatbox.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/chat.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet" >
<link href="<?php echo Cit_Server::getContent()->host; ?>css/uploaderPreviewer.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/responsive.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/DataTablepl.css" rel="stylesheet" type="text/css" />

<link href="<?php echo Cit_Server::getContent()->host; ?>css/jquery-ui.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/responsiveslides.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>css/map.css">
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>js/mapplic/mapplic.css">
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>css/popModal.css">
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>css/croppic.css">
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>css/jquery.capSlide.css">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/footable-0.1.css" rel="stylesheet" type="text/css" />
<link href="<?php echo Cit_Server::getContent()->host; ?>css/footable.sortable-0.1.css" rel="stylesheet" type="text/css" />
<link href="<?php echo Cit_Server::getContent()->host; ?>css/footable.paginate.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php echo Cit_Server::getContent()->host; ?>css/superslides.css"> 

<!--<link rel="stylesheet" type="text/css" href="<?php //echo Cit_Server::getContent()->host; ?>css/style_2.css">-->
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap.min.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/jquery.videoBG.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/colorbox/jquery.colorbox.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/datetimepicker/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/datetimepicker/locales/bootstrap-datetimepicker.es.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap-tab.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap-modalmanager.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/jquery_validate.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootbox.min.js?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.cookie.js?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/modernizr.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/DataTablepl.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/ajaxupload.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/vendor/modernizr-2.6.2.min.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/jquery-ui.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/responsiveslides.min.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/encrypte.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/jquery.watermarkinput.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/hammer.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.easing.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/mapplic/mapplic.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.inputfocus-0.9.min.js"></script>
<script src="<?php echo Cit_Server::getContent()->host; ?>js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jssor.core.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jssor.utils.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jssor.slider.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.ui.chatbox.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/chatboxManager.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/chat.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/popModal.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/croppic.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.capSlide.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/modernizr.custom.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/jquery.hashchange.min.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/jquery.easytabs.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Cit_Server::getContent()->host; ?>css/component.css">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
 (adsbygoogle = window.adsbygoogle || []).push({
   google_ad_client: "ca-pub-1889569630228906",
   enable_page_level_ads: true
 });
</script>
<link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<!-- Start of Woopra Code -->

<script>
(function(){
        var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call","trackForm","trackClick"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/w.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)

})("woopra");
woopra.config({
    domain: 'valeplaza.com'
});
woopra.track();

</script>

<!-- End of Woopra Code --> 