<!--<p>LIMPO</p>-->
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/custom.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.tooltipster.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.flagstrap.js"></script>
<link href="<?php echo Cit_Server::getContent()->host ?>css/flags.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.slimscroll.js"></script>
<style type="text/css">

.dropdown-menu {
    position: absolute;
    top: 0px;
    left: 33px !important;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 116px;
    padding: 5px 0 0px 0px;
    margin: 30px 0 0 !important;
    font-size: 14px;
    list-style: none;
    background-color: #ffffff;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
}
</style>
<style type="text/css">
.tooltipster-default {
	border-radius: 5px; 
	border: 2px solid #000;
	background: #4c4c4c;
	color: #fff;
}
.tooltipster-default .tooltipster-content {
	font-family: Arial, sans-serif;
	font-size: 14px;
	line-height: 16px;
	padding: 8px 10px;
	overflow: hidden;
}

/* This next selector defines the color of the border on the outside of the arrow. This will automatically match the color and size of the border set on the main tooltip styles. Set display: none; if you would like a border around the tooltip but no border around the arrow */
.tooltipster-default .tooltipster-arrow .tooltipster-arrow-border {
	/* border-color: ... !important; */
}


/* If you're using the icon option, use this next selector to style them */
.tooltipster-icon {
	cursor: help;
	margin-left: 4px;
}








/* This is the base styling required to make all Tooltipsters work */
.tooltipster-base {
	padding: 0;
	font-size: 0;
	line-height: 0;
	position: absolute;
	left: 0;
	top: 0;
	z-index: 9999999;
	pointer-events: none;
	width: auto;
	overflow: visible;
}
.tooltipster-base .tooltipster-content {
	overflow: hidden;
}


/* These next classes handle the styles for the little arrow attached to the tooltip. By default, the arrow will inherit the same colors and border as what is set on the main tooltip itself. */
.tooltipster-arrow {
	display: block;
	text-align: center;
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0;
	left: 0;
	z-index: -1;
}
.tooltipster-arrow span, .tooltipster-arrow-border {
	display: block;
	width: 0; 
	height: 0;
	position: absolute;
}
.tooltipster-arrow-top span, .tooltipster-arrow-top-right span, .tooltipster-arrow-top-left span {
	border-left: 8px solid transparent !important;
	border-right: 8px solid transparent !important;
	border-top: 8px solid;
	bottom: -7px;
}
.tooltipster-arrow-top .tooltipster-arrow-border, .tooltipster-arrow-top-right .tooltipster-arrow-border, .tooltipster-arrow-top-left .tooltipster-arrow-border {
	border-left: 9px solid transparent !important;
	border-right: 9px solid transparent !important;
	border-top: 9px solid;
	bottom: -7px;
}

.tooltipster-arrow-bottom span, .tooltipster-arrow-bottom-right span, .tooltipster-arrow-bottom-left span {
	border-left: 8px solid transparent !important;
	border-right: 8px solid transparent !important;
	border-bottom: 8px solid;
	top: -7px;
}
.tooltipster-arrow-bottom .tooltipster-arrow-border, .tooltipster-arrow-bottom-right .tooltipster-arrow-border, .tooltipster-arrow-bottom-left .tooltipster-arrow-border {
	border-left: 9px solid transparent !important;
	border-right: 9px solid transparent !important;
	border-bottom: 9px solid;
	top: -7px;
}
.tooltipster-arrow-top span, .tooltipster-arrow-top .tooltipster-arrow-border, .tooltipster-arrow-bottom span, .tooltipster-arrow-bottom .tooltipster-arrow-border {
	left: 0;
	right: 0;
	margin: 0 auto;
}
.tooltipster-arrow-top-left span, .tooltipster-arrow-bottom-left span {
	left: 6px;
}
.tooltipster-arrow-top-left .tooltipster-arrow-border, .tooltipster-arrow-bottom-left .tooltipster-arrow-border {
	left: 5px;
}
.tooltipster-arrow-top-right span,  .tooltipster-arrow-bottom-right span {
	right: 6px;
}
.tooltipster-arrow-top-right .tooltipster-arrow-border, .tooltipster-arrow-bottom-right .tooltipster-arrow-border {
	right: 5px;
}
.tooltipster-arrow-left span, .tooltipster-arrow-left .tooltipster-arrow-border {
	border-top: 8px solid transparent !important;
	border-bottom: 8px solid transparent !important; 
	border-left: 8px solid;
	top: 50%;
	margin-top: -7px;
	right: -7px;
}
.tooltipster-arrow-left .tooltipster-arrow-border {
	border-top: 9px solid transparent !important;
	border-bottom: 9px solid transparent !important; 
	border-left: 9px solid;
	margin-top: -8px;
}
.tooltipster-arrow-right span, .tooltipster-arrow-right .tooltipster-arrow-border {
	border-top: 8px solid transparent !important;
	border-bottom: 8px solid transparent !important; 
	border-right: 8px solid;
	top: 50%;
	margin-top: -7px;
	left: -7px;
}
.tooltipster-arrow-right .tooltipster-arrow-border {
	border-top: 9px solid transparent !important;
	border-bottom: 9px solid transparent !important; 
	border-right: 9px solid;
	margin-top: -8px;
}


/* Some CSS magic for the awesome animations - feel free to make your own custom animations and reference it in your Tooltipster settings! */

.tooltipster-fade {
	opacity: 0;
	-webkit-transition-property: opacity;
	-moz-transition-property: opacity;
	-o-transition-property: opacity;
	-ms-transition-property: opacity;
	transition-property: opacity;
}
.tooltipster-fade-show {
	opacity: 1;
}

.tooltipster-grow {
	-webkit-transform: scale(0,0);
	-moz-transform: scale(0,0);
	-o-transform: scale(0,0);
	-ms-transform: scale(0,0);
	transform: scale(0,0);
	-webkit-transition-property: -webkit-transform;
	-moz-transition-property: -moz-transform;
	-o-transition-property: -o-transform;
	-ms-transition-property: -ms-transform;
	transition-property: transform;
	-webkit-backface-visibility: hidden;
}
.tooltipster-grow-show {
	-webkit-transform: scale(1,1);
	-moz-transform: scale(1,1);
	-o-transform: scale(1,1);
	-ms-transform: scale(1,1);
	transform: scale(1,1);
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1);
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-moz-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-ms-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-o-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15);
}

.tooltipster-swing {
	opacity: 0;
	-webkit-transform: rotateZ(4deg);
	-moz-transform: rotateZ(4deg);
	-o-transform: rotateZ(4deg);
	-ms-transform: rotateZ(4deg);
	transform: rotateZ(4deg);
	-webkit-transition-property: -webkit-transform, opacity;
	-moz-transition-property: -moz-transform;
	-o-transition-property: -o-transform;
	-ms-transition-property: -ms-transform;
	transition-property: transform;
}
.tooltipster-swing-show {
	opacity: 1;
	-webkit-transform: rotateZ(0deg);
	-moz-transform: rotateZ(0deg);
	-o-transform: rotateZ(0deg);
	-ms-transform: rotateZ(0deg);
	transform: rotateZ(0deg);
	-webkit-transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 1);
	-webkit-transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 2.4); 
	-moz-transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 2.4); 
	-ms-transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 2.4); 
	-o-transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 2.4); 
	transition-timing-function: cubic-bezier(0.230, 0.635, 0.495, 2.4);
}

.tooltipster-fall {
	top: 0;
	-webkit-transition-property: top;
	-moz-transition-property: top;
	-o-transition-property: top;
	-ms-transition-property: top;
	transition-property: top;
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1);
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-moz-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-ms-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-o-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
}
.tooltipster-fall-show {
}
.tooltipster-fall.tooltipster-dying {
	-webkit-transition-property: all;
	-moz-transition-property: all;
	-o-transition-property: all;
	-ms-transition-property: all;
	transition-property: all;
	top: 0px !important;
	opacity: 0;
}

.tooltipster-slide {
	left: -40px;
	-webkit-transition-property: left;
	-moz-transition-property: left;
	-o-transition-property: left;
	-ms-transition-property: left;
	transition-property: left;
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1);
	-webkit-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-moz-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-ms-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	-o-transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15); 
	transition-timing-function: cubic-bezier(0.175, 0.885, 0.320, 1.15);
}
.tooltipster-slide.tooltipster-slide-show {
}
.tooltipster-slide.tooltipster-dying {
	-webkit-transition-property: all;
	-moz-transition-property: all;
	-o-transition-property: all;
	-ms-transition-property: all;
	transition-property: all;
	left: 0px !important;
	opacity: 0;
}


/* CSS transition for when contenting is changing in a tooltip that is still open. The only properties that will NOT transition are: width, height, top, and left */
.tooltipster-content-changing {
	opacity: 0.5;
	-webkit-transform: scale(1.1, 1.1);
	-moz-transform: scale(1.1, 1.1);
	-o-transform: scale(1.1, 1.1);
	-ms-transform: scale(1.1, 1.1);
	transform: scale(1.1, 1.1);
}
    
</style>
<script>
        $(document).ready(function() {
            $('.tooltip').tooltipster();
        });
    </script>
<!-- Start of Woopra Code -->

<script>
/*
(function(){

        var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call","trackForm","trackClick"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/w.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)

})("woopra");

 

woopra.config({

    domain: 'valeplaza.com'

});

woopra.track();*/

</script>

<!-- End of Woopra Code -->    
<script>
  
  /*(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-55157062-1', 'auto');
  ga('send', 'pageview');*/
</script>
<script>
var fb = {
    config :{
        app_id : <?php echo Zend_Registry::get('config')->facebook->appId; ?>, 
        use_xfbml : true,
        extendPermissions : 'public_profile, email, user_friends, publish_actions',
        locale : 'es_ES'
    },
    perms : [],
    hasPerm : function (perm) { for(var i=0, l=fb.perms.length; i<l; i++) { if(fb.perms[i] == perm) {return true;}} return false; },
    logged : false,
    user : false, // when login, is a user object: http://developers.facebook.com/docs/reference/api/user
    login : function (callback){
        FB.login(function(r) {
            if (r.status == 'connected') {
                FB.api('/me/permissions',function(perm){
                    fb.logged = true;
                    fb.perms = [];
                    for(i in perm.data[0]){
                        if (perm.data[0][i] == 1){
                            fb.perms.push(i);
                        }
                    }
                });    
                fb.getUser(callback);
            } else {
                fb.logged = false;
                fb.perms = [];
                callback();
            }
        },{scope:fb.config.extendPermissions});
        return false;
    },
    syncLogin : function (callback){
        if (!callback) callback = function(){};
        FB.getLoginStatus(function(r) {
            if (r.status == 'connected' ) {
                FB.api('/me/permissions',function(perm){
                    fb.logged = true;
                    fb.perms = [];
                    for(i in perm.data[0]){
                        if (perm.data[0][i] == 1){
                            fb.perms.push(i);
                        }
                    }
                });    
                fb.getUser(callback);
                return true;
            } else {
                fb.logged = false;
                callback();
                return false;
            }
        });
    },
    logout : function(callback) {FB.logout(callback);},
    getUser : function(callback){
        FB.api('/me', function(r){
            var user = r;
            user.picture = "https://graph.facebook.com/"+user.id+"/picture?type=large";
            fb.user=user; callback(user); 
        }); 
    },
    getFriends : function(callback){
        FB.api('/me/friends', function(r){
            callback( r.data );
        })
    },
    share : function(u_share, width_height){
        window.open('https://www.facebook.com/sharer/sharer.php?u='+u_share, 'facebook-share-dialog', width_height);
    },
    sendMessage : function(to, username, requestCallback){
        FB.ui({
            method:'send',
            to: to,
            link: 'https://www.valeplaza.com/perfil/'+username
        }, requestCallback );
    },
    publish : function (publishObj,callback,noReTry) {
        // publishObj: http://developers.facebook.com/docs/reference/api/post
        //alert("entroaa")
        //alert(fb.hasPerm('publish_actions'))
        if (fb.logged){
            FB.ui({
                method: 'share_open_graph',
                action_type: 'og.likes',
                action_properties: JSON.stringify({
                    object:publishObj
                })
                }, function(response){
                        if (!response || response.error) {
                            callback(false);
                        } else {
                            callback(true);
                        }
                });
        }else{
            if (!noReTry)
                return fb.login(function() { 
                    return fb.publish(publishObj,callback,1)
                });
            else{
                callback(false);
                return false;
            }
        }
        /*if (fb.logged && fb.hasPerm('publish_actions')){
            //alert("entro")
            
            /*FB.api('/me/feed', 'post', publishObj, function(response) {
                if (!response || response.error) {
                    //alert("entro1")
                    callback(false);
                } else {
                    //alert("entro2")
                    callback(true);
                }
            });*/
            /*return true;
        }else{ 
            //alert(noReTry)
            if (!noReTry)
                return fb.login(function() { 
                    return fb.publish(publishObj,callback,1)
                });
            else{
                callback(false);
                return false;
            }
        }*/
    },
    inviteFriends : function ( requestCallback){
        FB.ui({ 
            method: 'apprequests',
            message: 'Te invito a Life!'
        }, requestCallback );
    },
    readyFuncs : [],
    ready: function(func){fb.readyFuncs.push(func)},
    launchReadyFuncs : function () {for(var i=0,l=fb.readyFuncs.length;i<l;i++){fb.readyFuncs[i]();};}
}

function requestCallback2222(response){
    console.log(response, 'true');
    if(response){
        return true;
    }else{
        return false;
    }
}

window.fbAsyncInit = function() { 
  if (fb.config.app_id) FB.init({
      appId: fb.config.app_id, 
      status: true, 
      cookie: true, 
      xfbml: fb.config.use_xfbml,
      version: 'v2.2'
  });
  fb.syncLogin(fb.launchReadyFuncs);
};

/*(function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/all.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));*/
/*************************************************************/
</script>
<script>
    var URL="<?php echo Cit_Server::getContent()->host ?>";
    function v_mas(){
        text=$("#cajabusqueda").val();
        $(location).attr('href',URL+"buscar/"+text);
    }
</script>
<script type="text/javascript">
$(document).ready(function(){
    
    var URL="<?php echo Cit_Server::getContent()->host ?>";
    var liSelected;
    $('#cajabusqueda').on('keyup',function(event){
        
        if((event.which != "13" && event.which!= '40' && ( (event.which >= 49 && event.which <= 57) || (event.which > 64 && event.which<91) || event.which == 8 ) && event.which !='37' && event.which !='39' && event.which!='38' && event.which != "0" && $.trim($('#cajabusqueda').val()).length > 2)){
            var cajabusqueda = $(this).val();
            if(cajabusqueda !=''){
                $.ajax({
                    type: "POST",
                    url: "<?php echo Cit_Server::getContent()->host; ?>index/buscar",
                    data: {
                                'like':cajabusqueda
                            },
                    cache: false,
                    success: function(html)
                    {
                        $("#display").html(html).show();
                    }
                });
            }else{
                $("#display").html('').hide();
            }
        }else if(event.which === 40){
                    
                if(liSelected){
                    liSelected.removeClass('selected');
                    next = liSelected.next();
                    if(next.length > 0){
                        liSelected = next.addClass('selected');
                    }else{
                        liSelected = $('#display li').eq(0).addClass('selected');
                    }
                }else{
                    liSelected = $('#display li').eq(0).addClass('selected');
                }
        }else if(event.which === 38){
            if(liSelected){
                liSelected.removeClass('selected');
                next = liSelected.prev();
                if(next.length > 0){
                    liSelected = next.addClass('selected');
                }else{
                    liSelected = $('#display li').last().addClass('selected');
                }
            }else{
                liSelected = $('#display li').last().addClass('selected');
            }
        }else if(event.which == '13'){
			var nick = $('#display .selected').attr('data-url');
			if(nick!=null){
				$(location).attr('href',URL+"perfil/"+nick);
			}
		}
        return false;    
    });
    
    $('#display').mouseout(function(){
    $('body').click(function(){
        $("#display").html('').hide();
    });
    return false;
});
$('body').click(function(e){
    var target = $(e.target), article;
    
    if(target.is('#lnk-notificaciones') || target.is('.notificaciones')) {
        
    
    }else {
        if($('.notificaciones').is(':visible')) {
            $(".notificaciones").hide()
        }
    }
    
    if(target.is('#lnk-mensajes') || target.is('.neomensajes')){
    
    }else{
        if($('.neomensajes').is(':visible')) {
            $(".neomensajes").hide()
        }
    }
});
  $(function(){
      $('#div-scroll').slimScroll();
      $('#div-scroll2').slimScroll();
    });
});
jQuery(function($){
//$("#cajabusqueda").Watermark("Buscar");
});
</script>
<script>
$(document).ready(function(){
if ($('#uploadLogoHeader').length) {
var button = $('#uploadLogoHeader'), interval;
new AjaxUpload(button,{
action: '../../../index/uploadlogocli',
name: 'image',
onSubmit : function(file, ext){
//button.text('Subiendo');
$("#sp_logo_head").text('Subiendo')
this.disable();
interval = window.setInterval(function(){
var text = button.text();
if (text.length < 11){
button.text(text + '.');
} else {
$("#sp_logo_head").text('Subiendo')
}
}, 200);
},
onComplete: function(file, response){
$("#sp_logo_head").text('Cambiar foto')
window.clearInterval(interval);
// Habilitar boton otra vez
this.enable();
location.reload();
}
});
}
});
</script>
<script>
$(document).ready(function(){
    var num_noti=<?php echo $this->newNotificaciones; ?>;
$("#lnk-notificaciones").click(function(){
    if($('.notificaciones').is(':visible')) {
        $(".notificaciones").hide()
    }else {
        if(num_noti>0){
        $.ajax({
                type: 'post',
                url: '<?php echo Cit_Server::getContent()->host; ?>index/leernoti',
                success: function(json) {
                    num_noti=0;
                    $(".header-noti").css("display","none");
                    $(".notificaciones").show();
                }
            })
        }else{
            $(".notificaciones").show();
        }
        
    }
    
    if($(".neomensajes").is(':visible')) {
        $(".neomensajes").hide()
    }
})
$("#lnk-mensajes").click(function(){
if($(".neomensajes").is(':visible')) {
$(".neomensajes").hide()
}else{
$(".neomensajes").show()
}
if($(".notificaciones").is(':visible')) {
$(".notificaciones").hide()
}
})
$("#lnk_aceptar_sol").click(function(){
var usu= $("#lnk_aceptar_sol").attr('data-id')
$.ajax({
type: 'post',
url: '../../../index/responder',
data:{
'usuID':usu,
'tipo': 'a'
},
success: function(json) {
$("#row_u_"+usu).remove();
bootbox.alert("Felicidades tienes un nuevo amigo!",function(){
location.reload();
});
}
})
})
$("#lnk_rechazar_sol").click(function(){
var usu= $("#lnk_rechazar_sol").attr('data-id')
$.ajax({
type: 'post',
url: '<?php echo Cit_Server::getContent()->host; ?>index/responder',
data:{
'usuID':usu,
'tipo': 'r'
},
success: function(json) {
$("#row_u_"+usu).remove();
location.reload();
}
})
})
})
</script>
<header id="header" class="clearfix header_clientes" role="banner" >
    <div class="header-rel">
<div class="logo_in">
    <img class="logovph" src="<?php echo Cit_Server::getContent()->host?>headerfinal/headervp.png">
</div>
<div class="buscador buscador2">
<!--<div class="dropdown"> <a href="#" data-toggle="dropdown" role="button"><img src="../../../img/flag-ecuador.png" alt="Ecuador" title="Ecuador" /> Ecuador <b class="caret2"></b></a>
<ul role="menu" class="dropdown-menu">
<li><a href="#" role="menuitem"><img src="../../../img/flag-ecuador.png" alt="Ecuador" title="Ecuador" /> Ecuador</a></li>
</ul>
</div>-->
    <input type="submit" value="Buscar" style="border: 1px solid #c8c8c8;margin-left:25px;background: url(../img/newlup-01.png) 0 0 no-repeat #fff;background-position: 1px 0px;">
    <input type="search" placeholder="Buscar tiendas, vales y/o productos" class="buscar extrav4b" id="cajabusqueda"maxlength="100" name="b" 
           style="margin-left:0px !important;border-left:0px;border-right:1px solid #c8c8c8
           ">

<div id="display" class="display-buscador">
</div>
</div>

<!--<div class="barra-nivel pull-right">
<div class="progress">
<div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%;">
<span class="sr-only">500 vp</span>
</div>
</div>
</div>-->      
<div class="btn-gf">
    <a data-toggle="modal" data-target="#Compartirhead" href="#">
        <img src="<?php echo Cit_Server::getContent()->host?>iconosconf/gif-puntos.gif"> 
    </a>
</div>

<div class="cont-header">
    <div id="click" src="<?php echo Cit_Server::getContent()->host?>img/vps2-01.png"> 
        <div class="div-header1">
            <img class="img-headerp" onclick="document.location.href='<?php echo Cit_Server::getContent()->host; ?>transacciones'" src="<?php echo Cit_Server::getContent()->host?>headerfinal/vp.png" class="cpon">
        </div>
        <div class="count-vp3-cli ">
        <ul onclick="document.location.href='<?php echo Cit_Server::getContent()->host; ?>transacciones'">
        <li><?php echo $this->cm;?></li>
        <li><?php echo $this->dm;?></li>
        <li><?php echo $this->um;?></li>
        <li><?php echo $this->c;?></li>
        <li><?php echo $this->d;?></li>
        <li><?php echo $this->u;?></li>
        </ul>
        </div>
    </div>
    <div class="user-msj pos-rel">
        <div class="neomensajes neocli" >
             <img class="flech-ns" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/flech-n.png">
            <div class='s_amistad'><p style='padding:5px;text-align:center;'>Mensajes</p></div>
        <?php if(empty($this->Messages)):?>
        <?php echo  "<div class='treci'><img src='../img/mensajex-01.png'></div><span>No hay mensajes</span>". ""; ?>
        <?php else: echo  "<div id='div-scroll' class='cont-inf-head'>".$this->Messages."</div>";?>

        <?php endif;?>   
         
            <!--<div class='paddnew'><div class='r_left'></div><div class='vernew'> <a class="cpon">ver todos</a></div></div>-->
        </div>
        <div class="icon-msj" title="Mensajes" id="lnk-mensajes"></div>
        <span class="header-message" href="#" id="lnk-mensajes" <?php if(!empty($this->newMessages)):?> style="display:block"<?php endif;?>><?php if(!empty($this->newMessages)): echo $this->newMessages;  endif;?></span>
    </div>
<!--<ul class="user-info ">
<!--<li class="i-seguidores" >
<div class="dropdown">
<a href="#" id="lnk-notificaciones" <?php //if(!empty($this->newNotificaciones)):?>class="noti-available" <?php //endif;?> >
    <span class="header-noti" href="#" id="lnk-notificaciones" <?php //if(!empty($this->newNotificaciones)):?> style="display:block"<?php //endif;?>><?php //if(!empty($this->newNotificaciones)): echo $this->newNotificaciones;  endif;?></span></a>
</div> 
</li>-->
<li class="i-mensajes pos-rel">
    <div class="notificaciones noticli" style="text-align: center;">
         <img class="flech-ns" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/flech-n.png">
        <div class='s_amistad'>
            <p style='padding:5px;text-align:center;'>Notificaciones</p>
        </div>
        <?php if(empty($this->notificaciones)):?>
        <?php echo  "<div class='no-h'><div class='treci'><img src='../img/amistad-01.png'></div><div><span>No hay notificaciones</span></div></div>"; ?>
        <?php else: echo "<div id='div-scroll2' class='cont-inf-head'>".$this->notificaciones."</div>";?>
        <?php endif;?>   
    </div>
<div class="user-noti">   
    <div id="lnk-notificaciones" title="Notificaciones" class="icon-noti"></div>
    <span class="header-noti" href="#" <?php if(!empty($this->newNotificaciones)):?> style="display:block"<?php endif;?>><?php if(!empty($this->newNotificaciones)): echo $this->newNotificaciones;  endif;?></span>
</div>
</li>
<div class="div-header2">
    <img id="src_logo_head_up"src="<?php echo Zend_Registry::get('Susuario')->urlLogo; ?>" alt="Avatar" title="Avatar" class="avatar_stilo">
</div>
<div class="div-header3">
<div class="dropdown ">
<a class="icon_desp icon_desp2" href="#" data-toggle="dropdown" role="button">
<?php echo ucwords(Zend_Registry::get('Susuario')->data['nombre']);?><b class="caret"></b></a>
    <div  role="menu" class="dropdown-menu  socio2_c" style="padding:0;">
<ul role="menu" style="margin:0;">
<!--<div id="icon_rank"  title='<?php echo "Nivel: ".Zend_Registry::get('Susuario')->data['nivcli_titulo'] ?>' class="tooltip icon-nivel-big <?php echo Zend_Registry::get('Susuario')->data['nivcli_clase'].'-big'; ?>" >
</div>
<div class="n_reg"></div>
<div class="log">
    <p class="log_al">Logros obtenidos :</p>
    <div id="content-next-logros" class="next-logros">
    <?php if(!empty($this->mis_trofeos)): ?>
    <?php $i=0;foreach ($this->mis_trofeos as $key => $value): ?>
    <?php if($i<=7):?>
    <img class="logros_small tooltip" title='<?php echo "Logro: ".$value['trofeo_nombre']; ?>' src="<?php echo Cit_Server::getContent()->host.'logros/'.$value['trofeo_id'].'_small.png'; ?>"/>
    <?php else: break; ?>
    <?php endif;?>
    <?php $i++;endforeach;?>
    <?php endif;?>
    </div>
</div>
<div class="log2"><p class="log_al2">Logros por alcanzar :</p>
<div id="content-next-logros" class="logros_al">
<?php if(!empty($this->next_trofeos)): ?>
<?php foreach ($this->next_trofeos as $key => $value): ?>
<img  title='<?php echo $value['trofeo_descripcion']; ?>' class="  logros_small tooltip"  
src="<?php echo Cit_Server::getContent()->host.'logros/'.$value['trofeo_id'].'_small.png'; ?>"/>
<?php endforeach;?>
<?php endif;?>
</div>
</div>-->
<div class="div_Rank">
<span>
<a href="../../../socio/misdatos" role="menuitem" class="a_config">
<i  class="icon icon-config-black"></i>
<span class="span-con">Mi cuenta</span></a>
    <a href="<?php echo $this ->baseUrl('outh/logout'); ?>" role="menuitem" class="a_config">
        
        <i class="icon icon-logout"></i> 
        <span >Salir</span></a>
</span> 
</div>
<!--<div class="div_am"> <p class="p_rank"> Ranking</p></div>
<div class="list_amig">
<?php //if(!empty($this->listRanking)): ?>
<?php //$i=1;?>
<?php //foreach ($this->listRanking as $key => $value): ?>
    <?php //if($i<=10):?>
<ul class="fila_ram">
<li><p class="ra_num"><?php //echo $i; ?></p>
    <img  width="25" height="25" class="ra_img" 
src="<?php /*if (!empty($value['cliente_logo'])) {
        /echo Cit_Server::getStatic()->host."imagenes/clientes/" .$value['cliente_id'] . "/logo/" . $value['cliente_logo'];
    } else {
        echo Cit_Server::getContent()->host."img/avatar-50x50.png";
    }*/ ?>" >
<span><a  class="ra_nom" 
href="<?php //echo Cit_Server::getContent()->host.'perfil/'.$value['cliente_nick']; ?>">
<?php //echo $value['cliente_nombre']?></a></span>
<div class="icon-nivel-small <?php //echo $value['nivcli_clase'].'-small'; ?>"></div>
<div id="content-next-logros" class="logritos_1">

</div>
</li>
</ul>
    <?php //endif;?>
<?php //$i++;endforeach; ?>
<?php //endif; ?>   
   
</div>-->
<!--
<li><a href="#" role="menuitem" id="uploadLogoHeader"><i class="icon icon-picture"></i><span id="sp_logo_head">Cambiar foto</span></a></li>-->
</ul>
</div>
</div>
</div>
</div>
    
    </div>
</header>
<script>
//$('#display li').eq(0).addClass('selected')
//$(window).load(function(){
    //var li = $('#display li');
    
    /*$(window).keydown(function(e){
        
                
            });*/
//})
</script>
<!--<script>
 window.intercomSettings = {
   app_id: "qvpl4myv",
   name: "<?php //echo Zend_Registry::get('Susuario')->data['nombre']?>", // Full name
   email: "<?php //echo Zend_Registry::get('Susuario')->data['usuario_email']?>", // Email address
   created_at: "<?php //echo strtotime(Zend_Registry::get('Susuario')->data['fecha_registro']) ?>",// Signup date as a Unix timestamp
   user_hash:"<?php //echo hash_hmac('sha256', Zend_Registry::get('Susuario')->data['usuario_email'], '4a0r1-jtuwZxh5XcGhn8KLgzelCup4vSc270oUet'); ?>"
 };
</script> 
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/qvpl4myv';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>
-->
