 
<header id="header" role="banner">
    <div class="header-landing-container ">
        <div class="header-landing-logo">
            <a href="/"></a> 
        </div>
        <div class="header-menu">
            
            <a id="menua" data-toggle="modal" data-target="#IniciarSesion2" href="#">Registro del usuario</a>
            <a id="menua" data-toggle="modal" data-target="#IniciarSesion" href="#">Login</a>
        </div> 
        <div class="header-logo">
            <a href="https://www.facebook.com/ValeplazaPeru/"  target="_blank">
                <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/face.png">
            </a>
            <a href="https://www.twitter.com/@VPValeplaza"  target="_blank">
                <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/twi.png"> 
            </a>
            <a href="https://www.instagram.com/valeplazaperu/"  target="_blank">
                <img class="move-im" src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/insta.png"> 
            </a>
          <!--  <a href="whatsapp://send?text=973958780" data-action="share/whatsapp/share">-->
            <img src="<?php echo Cit_Server::getContent()->host; ?>headerfinal/what.png"> 
           <!-- </a>-->
            <span class="tx-what">Whatsapp:</span>
            <span class="tx-whatnum">973958780</span>
        </div>

    </div>
</header>
<div class="modal fade" id="IniciarSesion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-content-log">
            
            <div class="cont-log-mdl">
                <div class="fil-log-mdl">
                    <img class="fon-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/img2.jpg">
                    <div class="tx-fon-log">
                        <p class="tx-fon-1" ><span class="rou-bld">BIENVENIDO</span><span>.</span></p>
                        <p class="tx-fon-2">Empieza a disfrutar y a vivir una nueva experiencia en la Red Mercaderos.</p>
                    </div>
                </div>
                <div class="fil-log-mdl">
                    <div class="cont-fil-log-mdl">
                        <form method="post" id="frm-login">
                        <p class="titu-log-mdl">Iniciar Sesión</p>
                        <p class="tx-ing-log">Para ingresar deberás estar registrado como usuario en Mercaderos</p>
                        <div class="cont-inpt-log-mdl">
                            <input id="header_correo"  class="inpt-log-mdl" type="text" placeholder="Correo electrónico" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input id="header_pass" class="inpt-log-mdl" type="password" placeholder="Contraseña" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input type="checkbox" name="recordarme" <?php if(!empty($this->vp_recordar)) echo "checked='checked'"; ?> id="recordarme" class="left">
                            <p class="record">Recordarme</p>
                        </div>
                        <input type="submit" class="btn-ing" value="Ingresar">
                        <div class="modal-term-log">
                            <a href="<?php echo Cit_Server::getContent()->host."recuperar-password"?>"><span class="hov">Recordar <b>CONTRASEÑA</b></span></a>
                           <p class="obten-ayuda">¿Aún no tienes cuenta? <b id="modal_session_tienda" class="hov-subr cpon">REGÍSTRATE AQUÍ</b></p>
                        </div>
                        <div>
                            <img class="linea-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/linea.png">
                        </div> 
                         <div class="cont-fb-log" id="a_login_fb"><img src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/btnfb.png"></div>
                    </form>
                    </div>
                </div>
            </div>
        </div>

<!-- /.modal-dialog --> 
</div>
    <div class="modal fade" id="IniciarSesion2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-content-log">
            
            <div class="cont-log-mdl">
                <div class="fil-log-mdl">
                    <img class="fon-log" src="<?php echo Cit_Server::getContent()->host; ?>iconosconf/img-login/img1.jpg">
                    <div class="tx-fon-log">
                        <p class="tx-fon-1" ><span class="rou-bld">BIENVENIDO</span><span>.</span></p>
                        <p class="tx-fon-2">Empieza a disfrutar y a vivir una nueva experiencia en la Red Mercaderos.</p>
                    </div>
                </div>
                <div class="fil-log-mdl">
                    <div class="cont-fil-log-mdl">
                        <form method="post" id="form-reg-cli">
                        <p class="titu-log-mdl">Regístrate</p>
                        <div class="cont-inpt-log-mdl">
                            <input id="alias_usu" name="alias_usu" class="inpt-log-mdl" type="text" placeholder="Alias" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input type="email" id="email_usu" name="email_usu" class="inpt-log-mdl" placeholder="Correo electrónico" >
                        </div>
                        <div class="cont-inpt-log-mdl">
                            <input type="password" id="password_usu" name="password_usu" class="inpt-log-mdl" placeholder="Contraseña" >
                        </div>
                        <input type="hidden" id="h_fb"/>
                        <input type="submit" class="btn-ing" value="Ingresar">
                        <div class="modal-term-log">
                            <span>Accediendo acepto los términos y condiciones y las</span>
                            <br>
                            <a href="<?php echo Cit_Server::getContent()->host.'privacidad'; ?>" target="_blank"><b class="hov">Políticas de privacidad</b></a>
                        </div>
                        <a href="<?php echo Cit_Server::getContent()->host ?>planes">
                        <div class="btn-reg-log-tie">Regístrate como tienda aquí</div>
                        </a>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <script src="../js/jquery.flagstrap.js"></script>

<script>
    
    

    /*$('#options').flagStrap({
        countries: {
            "AU": "Australia",
            "GB": "United Kingdom",
            "US": "United States"
        },
        buttonSize: "btn-sm",
        buttonType: "btn-info",
        labelMargin: "10px",
        scrollable: false,
        scrollableHeight: "350px"
    });

    $('#advanced').flagStrap({
        buttonSize: "btn-lg",
        buttonType: "btn-primary",
        labelMargin: "20px",
        scrollable: false,
        scrollableHeight: "350px"
    });*/
    </script>
<script>
/*$('#a_conect_fb').on('click', function(){
    if(fb.logged){
        $("#nom_usu").val(fb.user.first_name);
        $("#ape_usu").val(fb.user.last_name);
        $("#email_usu").val(fb.user.email);
    }else{
        fb.login(function(){
            if(fb.logged){
                $("#nom_usu").val(fb.user.first_name);
                $("#ape_usu").val(fb.user.last_name);
                $("#email_usu").val(fb.user.email);
            }
        });
    }
});*/
$("#slpais").change(function(){
    $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>index/getprovi',
            data:{
                    'pais': $("#slpais").val()
                },
            success: function(json) {
                    $("#slciudad").empty();
                    $("#slciudad").append("<option value=''>Selecciona tu ciudad</option>")
                        result=jQuery.parseJSON(json);
                        $(result).each(function(k, v){
                            $("#slciudad").append("<option value='"+v.prov_id+"'>"+v.prov_nombre+"</option>")
                        });         
                }
        })
});
$("#modal_session_tienda").click(function(){
    $("#IniciarSesion").modal("hide");
    $("#IniciarSesion2").modal("show");
});

$('#frm-login').validate({
    rules:{
        header_pass : {    
            required : true //para validar campo vacio
        },
        header_correo : {    
            required : true,
            email:true//para validar campo vacio
        }
    },
    messages:{
        header_pass : {    
            required : 'Falta indicar el password' //para validar campo vacio
        },
        header_correo : {  
            required    : "Falta indicar su correo electrónico",
            email  : "Ingrese un formato correcto de correo"//para validar formato email
        }
    }, 
    highlight: function(element) {
        $(element).addClass('errorborde');
    }, 
    unhighlight: function(element) {
        $(element).removeClass('errorborde');
    },
    submitHandler: function(form) {
        if($("#recordarme").is(":checked")){
            rec=1;
        }else{
            rec=0
        }
        $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>outh/login',
            data:{
                'password':$("#header_pass").val(),
                'email':$("#header_correo").val(),
                'rec':rec
            },
            beforeSend:function(objeto){
                $('#bloquea').css("display",'block');
            },
            success: function(json) {
                $('#bloquea').css("display",'none');
                var response =  jQuery.parseJSON(json);
                //alert(response.nick)
                    responce = jQuery.isEmptyObject($.trim(response.nick))
                    if(responce){
                         cad="";
                        $(response.mensajes).each(function(k, v){
                            cad=v.mail
                        })
                        bootbox.alert(cad);
                    }else{
                        document.location.href="<?php echo Cit_Server::getContent()->host.$this->urlRedirect; ?>";
                       
                    }
                }
        });        
        return false;                                
    }                        
});

$('#form-reg-cli').validate({
    rules:{
        alias_usu : {    
            required : true //para validar campo vacio
        },
        email_usu : {    
            required : true,
            email:true//para validar campo vacio
        },
        password_usu : {    
            required : true //para validar campo vacio
        }
    },
    messages:{
        alias_usu : {    
        //para validar campo vacio
            required    : "Falta indicar su alias"  //para validar formato email
        },
        email_usu : {    
        //para validar campo vacio
            required    : "Falta su correo electrónico",
            email  : "Ingrese un formato correcto de correo"//para validar formato email
        },
        password_usu : {    
        //para validar campo vacio
            required    : "Falta indicar su contraseña"  //para validar formato email
        }
    }, 
    highlight: function(element) {
        $(element).addClass('errorborde');
    }, 
    unhighlight: function(element) {
        $(element).removeClass('errorborde');
    },
    submitHandler: function(form) {
        $.ajax({
            type: 'post',
            url: '<?php echo Cit_Server::getContent()->host; ?>outh/registrocliente',
            data:{
                'alias_usu':$("#alias_usu").val(),
                'email_usu':$("#email_usu").val(),
                'password_usu':$("#password_usu").val(),
                'fb':$("#h_fb").val()
            },
            beforeSend:function(objeto){
                $('#bloquea').css("display",'block');
            },    
            success: function(json) {
                $('#bloquea').css("display",'none');
                var response =  jQuery.parseJSON(json);
                if(response.status){
                    bootbox.alert(response.mensaje,function(){
                        location.reload();
                    })
                }else{
                    bootbox.alert(response.mensaje);
                }
            }
        });        
        return false;
    }                  
});
</script>