<link href="<?php echo Cit_Server::getContent()->host; ?>css/stilos.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/Bienvenido.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<!--<link href="<?php echo Cit_Server::getContent()->host; ?>css/nav_cliente.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/nav_empresa.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
-->
<link href="<?php echo Cit_Server::getContent()->host; ?>css/bootstrap.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/bootstrap.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/bootstrap-responsive.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/bootstrap-modal.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<link href="<?php echo Cit_Server::getContent()->host; ?>css/bootstrap-datetimepicker.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/style.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/themes/jquery.ui.all.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/themes/jquery.ui.autocomplete.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<!--<link href="<?php echo Cit_Server::getContent()->host; ?>css/admin.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/custom-theme/jquery-ui-1.8rc2.custom.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<link href="<?php echo Cit_Server::getContent()->host; ?>css/uploaderPreviewer.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/responsive.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/jquery.dataTables.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<link href="<?php echo Cit_Server::getContent()->host; ?>css/jquery-ui.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/jflow.plus.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<!--<link href="<?php //echo Cit_Server::getStatic()->host; ?>css/jquery.bxslider.css?v=<?php //echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">-->
<link href="<?php echo Cit_Server::getContent()->host; ?>css/responsiveslides.min.css?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>" rel="stylesheet">

<!--<link href="//code.jquery.com/ui/1.10.4/themes/smoothness/.css" rel="stylesheet">-->
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/jquery.min.js"></script>-->
<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host; ?>js/jquery-1.9.1.js"></script>-->
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/custom.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/colorbox/jquery.colorbox.js"></script>

<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host; ?>js/datetimepicker/bootstrap.min.js"></script>-->
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/datetimepicker/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/datetimepicker/locales/bootstrap-datetimepicker.es.js"></script>
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host; ?>js/datetimepicker/respond.min.js"></script>-->

<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap-tab.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootstrap-modalmanager.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/jquery_validate.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host; ?>js/bootbox.min.js?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>"></script>
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/upload/jquery-ui-1.8rc2.custom.min.js"></script>
<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/upload/uploaderPreviewer.js"></script>
<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/upload/itemForm.js"></script>
<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/upload/globalFunctions.js"></script>-->
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.cookie.js?v=<?php echo Zend_Registry::get('config')->version->cssJs ?>"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/modernizr.js"></script>
<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/jquery.dataTables.js"></script>

<script type="text/javascript" src="<?php echo Cit_Server::getContent()->host ?>js/ajaxupload.js"></script>
<!--<script src="//j.maxmind.com/js/apis/geoip2/v2.0/geoip2.js" type="text/javascript"></script>-->
<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBaWR_5n0nXV7-xE0uwLdZR5CKnmaxDnTk&sensor=true&libraries=geometry"></script>-->
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/maps.google.polygon.containsLatLng.js"></script>-->
<!--<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry&sensor=false"></script>-->
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host; ?>js/tiny_mce/jquery.tinymce.js"></script>-->
<!--<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/autocomplete/jquery.ui.core.js"></script>
<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/autocomplete/jquery.ui.widget.js"></script>
<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/autocomplete/jquery.ui.position.js"></script>
<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/autocomplete/jquery.ui.menu.js"></script>
<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/autocomplete/jquery.ui.autocomplete.js"></script>-->
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host ?>js/valeplaza.js"></script>-->
<!--<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/jquery-1.9.1.js"></script>-->
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/vendor/modernizr-2.6.2.min.js"></script>
<script type="text/javascript"src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<!--<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/jquery-ui.js"></script>-->
<!--<script type="text/javascript" src="<?php //echo Cit_Server::getStatic()->host; ?>js/bootstrap-modal.js"></script>-->
<!--<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/jflow.plus.js"></script>-->
<!--<script type="text/javascript"src="<?php //echo Cit_Server::getStatic()->host ?>js/jquery.bxslider.js"></script>-->
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/responsiveslides.min.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/encrypte.js"></script>
<script type="text/javascript"src="<?php echo Cit_Server::getContent()->host ?>js/jquery.watermarkinput.js"></script>
