<style type="text/css">



    body{margin:0; font-size:75%; line-height:1.42857; color:#626262; font-family:Arial,Helvetica,sans-serif; }

    p{
        font-size: 12px;
        line-height: 120%;
        margin: 0 0 13px;
        font-family: Arial, Helvetica, sans-serif;
        color: #505050;
    }




</style>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr> <br>
                <td valign="top">
                    <h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; ">¡<?php echo $this->tienda; ?> acaba de enviar su pedido a la siguiente direccion!</h1>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; "><?php echo $this->direccion; ?></p>
                    <br>
                    <div class="other">       

                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; ">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />          

                    </div>
                <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
    </tr>
</table></td>
</tr>
<tr>
    <td style="font-size:0; line-height:0; padding:0"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
</tr>
</table>


