<!--Hola <?php //echo $this->usuario['nombre']; ?><br/>
bienvenido a valeplaza.<br/>
Para confirmar su registro haz click sobre el siguiente enlace:<br/>
<a href="<?php //echo Cit_Server::getContent()->host ?>tienda/confirmacion/codigo/<?php //echo  $this->usuario['codigo']; ?>">
<?php //echo  Cit_Server::getContent()->host ?>tienda/confirmacion/codigo/<?php //echo  $this->usuario['codigo']; ?>
</a><br/>

Un saludo,<br/>
Tu equipo valeplaza.-->

<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td valign="top">
                    	<h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif;color:#008BD2; margin:27px 0 14px">¡Bienvenido <?php echo $this->usuario['nombre']; ?>!</h1>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; margin:0 0 15px">Acabas de solicitar el registro en nuestro sistema.<br />
                            Por favor haz click en el siguiente enlace para completar su registro :</p>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 15px;font-size:15px"><a href="<?php echo Cit_Server::getContent()->host ?>confirma/<?php echo  $this->usuario['codigo']; ?>" style="color:#5571b3; text-decoration:underline"><?php echo Cit_Server::getContent()->host."confirma/". $this->usuario['codigo']; ?></a></p>
                        <!--<p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 15px">Conozca más sobre nuestro sistema: <a href="#" style="color:#5571b3; text-decoration:underline">link del video</a></p>-->
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 30px">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />
                                                    <!--  <a href="#" style="color:#5571b3; text-decoration:underline">Ayuda y soporte</a>--></p></td>
                    <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
                </tr>
            </table></td>
    </tr>
    <tr>
       <td style="font-size:0; line-height:0; padding:0"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
    </tr>
</table>

