<style type="text/css">
body{margin:0; font-size:75%; line-height:1.42857; color:#626262; font-family:Arial,Helvetica,sans-serif; }

p{
font-size: 12px;
line-height: 120%;
margin: 0 0 13px;
font-family: Arial, Helvetica, sans-serif;
color: #505050;
}
</style>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td>
            <table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr> <br>
                    <td valign="top">
                        <h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; ">¡Felicidades <?php echo $this->reserva['nombre']; ?> tu vale ha sido canjeado!</h1>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; ">Esperamos que hayas disfrutado tu compra.</p>


                        <table style="width: 471px;height: auto; border: 1px solid #c8c8c8;border-radius: 5px;">
                            <tr>
                                <td style="width: 122px;height: 70px;padding: 20px 10px 20px 20px;">
                                    <?php if(!empty($this->reserva['pim_url'])) $cadUrl= Cit_Server::getStatic()->host."imagenes/producto/".$this->reserva['producto_id']."/".$this->reserva['pim_url']; else $cadUrl=Cit_Server::getContent()->host."img/avatar-50x50.png";?>
                                    <img width="120px" height="70px" src="<?php echo $cadUrl; ?>">
                                </td> 
                                <td style="width: 425px;height: 70px;padding: 20px 20px 20px 0px;">
                                    <span  style="font-size:13px;color:#5F5F5F;font-size:15px;font-weight: bold;"><?php echo $this->reserva['oferta_titulo']; ?></span><br>
                                    <span  style="font-size:11px;color:#5F5F5F;font-size:12px;font-weight: bold;"><?php echo $this->reserva['tienda_nombre']; ?></span><br>
                                    <span style="font-size: 10px;">Valeplaza:</span><span style="font-size: 10px;"><?php echo $this->reserva['mall_nombre']; ?></span><br>
                                    <span style="font-size: 10px;" >Fecha de publicación:</span><span style="font-size: 10px;"><?php echo $this->reserva['oferta_inicio']; ?></span><br>
                            </tr>   
                        </table><br> 
                        <table style="width: 471px;height: auto;border-radius: 5px;border: 1px solid #c8c8c8;border-radius: 5px;">
                            <tr>
                                <td style="width: 205px;height: 70px;padding: 20px 5px 20px 20px;" >
                                    <span>Codigo de Vale:</span><br>
                                    <span>Precio:</span><br>                   
                                    <span>puntos:</span>                      
                                </td>        
                                <td style="width: 425px;height: 70px;padding: 20px 20px 20px 0px;">
                                    <?php   
                                            $puntos = $this->reserva['oferta_puntos'];
                                            if ($this->reserva['producto_cambio'] == Obj_CpnProducto::CAMBIO_NO) {
                                                
                                                $precio_oferta = $this->reserva['oferta_precio'];
                                            } else {
                                                //$puntos = round($this->reserva['oferta_puntos'] * $this->cambio);
                                                $precio_oferta = round($this->reserva['oferta_precio'] * $this->cambio);
                                            }
                                            ?>
                                    <?php $cod=  substr($this->reserva['reserva_codigo'],5);$str1=substr($cod,0,5);$str2=substr($cod,5,5);$codigo=$str1." - ".$str2;?>
                                    <span style="color:#BB141B;font-weight: bold"><?php echo $codigo; ?></span><br>
                                    <span style="color:#61A75B;font-weight: bold" ><?php echo $this->moneda.$precio_oferta; ?></span><br>
                                    <span style="color:#E9B42B;font-weight: bold"><?php echo $puntos; ?></span>
                                    <img style="position: absolute;margin-left: 10px;margin-top: -2px;" src="<?php echo Cit_Server::getContent()->host; ?>img/vp-e-01.png">
                                </td>
                            </tr>
                        </table>
                        <div class="other">       
                        <br/>        
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; ">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />          

                    </div>
                <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
               
                
                    </td>
                    </tr>
                 
            </table>
        </td>
    </tr>
</table>
