<!--Hola <?php //echo $this->usuario['nombre']; ?><br/>
bienvenido a valeplaza.<br/>
Para confirmar su registro haz click sobre el siguiente enlace:<br/>
<a href="<?php //echo Cit_Server::getContent()->host ?>tienda/confirmacion/codigo/<?php //echo  $this->usuario['codigo']; ?>">
<?php //echo  Cit_Server::getContent()->host ?>tienda/confirmacion/codigo/<?php //echo  $this->usuario['codigo']; ?>
</a><br/>

Un saludo,<br/>
Tu equipo valeplaza.-->

<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td valign="top">
                    	<h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; margin:27px 0 14px">¡<?php echo $this->nombre." ".$this->apellido; ?> ha solicitado recibir informacion!</h1>
                        <p>Correo: <?php echo $this->correo; ?></p>
                        <p>Telefono: <?php echo $this->telefono; ?></p>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 30px">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />
                                                      <!--  <a href="#" style="color:#5571b3; text-decoration:underline">Ayuda y soporte</a>--></p></td>
                    <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
                </tr>
            </table></td>
    </tr>
    <tr>
       <td style="font-size:0; line-height:0; padding:0"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
    </tr>
</table>

