<style type="text/css">



    body{margin:0; font-size:75%; line-height:1.42857; color:#626262; font-family:Arial,Helvetica,sans-serif; }

    p{
        font-size: 12px;
        line-height: 120%;
        margin: 0 0 13px;
        font-family: Arial, Helvetica, sans-serif;
        color: #505050;
    }




</style>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr> <br>
                <td valign="top">
                    <h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; ">¡Felicidades <?php echo $this->reserva['nombre']; ?> acabas de seleccionar un vale!</h1>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; ">Aquí te dejamos los detalles de tu vale para que lo puedas canjear en los locales correspondientes</p>


                    <table style="width: 471px;height: auto; border: 1px solid #c8c8c8;border-radius: 5px;  ">
                        <tr>
                            <td style="width: 122px;height: 70px;padding: 20px 10px 20px 20px;">
                                <?php if(!empty($this->reserva['pim_url'])) $cadUrl= Cit_Server::getStatic()->host."imagenes/producto/".$this->reserva['producto_id']."/".$this->reserva['pim_url']; else $cadUrl=Cit_Server::getContent()->host."img/avatar-50x50.png";?>
                                <img width="120px" height="70px" src="<?php echo $cadUrl; ?>">
                            </td> 
                            <td style="width: 425px;height: 70px;padding: 20px 20px 20px 0px;">
                                <span  style="font-size:13px;color:#5F5F5F;font-size:15px;font-weight: bold;"><?php echo $this->reserva['oferta_titulo']; ?></span><br>
                                <span  style="font-size:11px;color:#5F5F5F;font-size:12px;font-weight: bold;"><?php echo $this->reserva['tienda_nombre']; ?></span><br>
                                <span style="font-size: 10px;">Valeplaza:</span><span style="font-size: 10px;"><?php echo $this->reserva['mall_nombre']; ?></span><br>
                                <span style="font-size: 10px;" >Fecha de publicación:</span><span style="font-size: 10px;"><?php echo $this->reserva['oferta_inicio']; ?></span><br>
                        </tr>   
                    </table>    
                    <br> 
                    <table style="width: 471px;height: auto;border-radius: 5px;border: 1px solid #c8c8c8;border-radius: 5px;">
                        <tr>
                            <td style="width: 205px;height: 70px;padding: 20px 5px 20px 20px;" >
                                <span>Codigo de Vale:</span><br>
                                <span>Precio:</span>   <br>                   
                                <span>puntos:</span>                      
                            </td>        
                            <td style="width: 425px;height: 70px;padding: 20px 20px 20px 0px;">
                                <?php 
                                if ($this->reserva['producto_cambio'] == Obj_CpnProducto::CAMBIO_NO) {
                                    $puntos = $this->reserva['oferta_puntos'];
                                    $precio_oferta = $this->reserva['oferta_precio'];
                                } else {
                                    $puntos = round($this->reserva['oferta_puntos'] * $this->cambio);
                                    $precio_oferta = round($this->reserva['oferta_precio'] * $this->cambio);
                                }
                                ?>
                                <?php $cod=  substr($this->reserva['reserva_codigo'],5);$str1=substr($cod,0,5);$str2=substr($cod,5,5);$codigo=$str1." - ".$str2;?>
                                <span style="color:#BB141B;font-weight: bold"><?php echo $codigo; ?></span>  <br>
                                <span style="color:#61A75B;font-weight: bold" ><?php echo $this->moneda.$precio_oferta; ?></span><br>
                                <span style="color:#E9B42B;font-weight: bold"><?php echo $puntos; ?></span>
                                <img style="position: absolute;margin-left: 10px;margin-top: -2px;" src="<?php echo Cit_Server::getContent()->host; ?>img/vp-e-01.png">
                            </td>
                        </tr>
                    </table>
                    <br>
                    <table style="width: 471px;height: auto;border-radius: 5px;border: 1px solid #c8c8c8;border-radius: 5px;">           
                        <center>
                            <td style="width: 315px;border-right: 1px solid #c8c8c8;height: 45px;padding: 10px;text-align: left;padding: 8px 20px 8px 10px;">
                                <span style="font-weight:bold;color: #5F5F5F;font-size: 15px;">Periodo de canje:</span><br>
                                <p  style="margin-top: 10px;" >del <?php echo $this->reserva['oferta_ini_canje']; ?>  hasta el <?php echo $this->reserva['oferta_caducidad']; ?></p>           

                            </td>
                        </center>
                        <td style="width: 112px;border-right: 1px solid #c8c8c8;height: 50px;border: none;padding: 6px 17px 10px 12px;">
                            <span style="font-weight:bold;color: #5F5F5F;font-size: 15px;">Bonos:</span><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                            <span style="font-size: 20px;"><?php echo $this->reserva['oferta_bono']; ?> </span>     
                        </td>

                    </table>                       
                    <br>
                    <table style="width: 471px;height: auto;border-radius: 5px;border: 1px solid #c8c8c8;border-radius: 5px;">
                        <tr>
                            <td style="width: 464px;height: 38px;border-bottom: 1px solid #c8c8c8;padding: 10px;">
                                <span style="color: #5F5F5F;font-size: 15px;">Términos de uso</span>
                            </td>
                        </tr>
                        <tr>
                            <td style="font-size: 12px;padding: 12px;text-align: justify"><?php echo $this->reserva['oferta_condiciones']; ?></td>
                        </tr>
                    </table>
                    <br>
                    <table style="width: 471px;height: auto;border-radius: 5px;border: 1px solid #c8c8c8;border-radius: 5px;">
                        <tr>
                            <td style="width: 464px;height: 38px;border-bottom: 1px solid #c8c8c8;padding: 10px;">
                                <span style="color: #5F5F5F;font-size: 15px;">Locales de canje</span>
                            </td>
                            <td style="width: 464px;height: 38px;border-bottom: 1px solid #c8c8c8;padding: 10px;">
                                <span style="color: #5F5F5F;font-size: 15px;   ">
                                    
                                </span>
                            </td>
                        </tr>
                        <?php if(!empty($this->reserva['direcciones'])): ?>
                        <?php foreach ($this->reserva['direcciones'] as $key => $value): ?>
                            <tr>
                                <td style="width: 464px;height: 38px;padding: 5px 20px 5px 20px;font-size: 15px;">
                                    <span style="color: #5F5F5F;font-size: 15px;"><?php echo $value['dir_nombre']; ?></span>
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 205px;height: 70px;padding: 0px 5px 20px 20px;" >
                                    <span>Dirección :</span><br>
                                    <span>Telefono :</span><br>
                                    <span>Horario de atención :</span><br>
                                    <span>Condiciones adicionales :</span>

                                </td>        
                                <td style="width: 625px;height: 70px;padding: 0px 5px 20px 0px;" >                  
                                    <span style="width: 260px;height: auto;"><?php echo $value['dir_direccion']; ?></span><br>
                                    <span style="width: 260px;height: auto;"><?php echo $value['dir_telefono']; ?></span>   <br>               
                                    <span style="width: 260px;height: auto;"><?php echo $value['dir_horario']; ?></span>  <br>       
                                    <span style="width: 260px;height: auto;"><?php echo $value['dir_condiciones']; ?></span>                              

                                </td>
                            </tr>
                        <?php endforeach;?>
                        <?php endif; ?>
                        
                    </table>
                    <div class="other">       

                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; ">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />          

                    </div>
                <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
    </tr>
</table></td>
</tr>
<tr>
    <td style="font-size:0; line-height:0; padding:0"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
</tr>
</table>


