<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td valign="top">
                    	<h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif;color:#008BD2; margin:27px 0 14px">Hola <?php echo $this->usuario['nombre']; ?></h1>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; margin:0 0 15px">Su oferta no ha superado los estándares de calidad que se requieren. Lo  invitamos a revisar el detalle  en el siguiente enlace (tiene que estar logueado en valeplaza):<br /><a href="http://www.valeplaza.com/vales/edit/id/<?php echo $this->usuario['oferta_id']?>"><?php echo $this->usuario['oferta_titulo'];?></a><br />
                        El administrador ha adjuntado la siguiente observacion:<br/><?php echo $this->usuario['observacion']; ?></p>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 15px;font-size:15px"><a href="http://www.valeplaza.com" style="color:#5571b3; text-decoration:underline">http://www.valeplaza.com</a></p>
                        <!--<p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 15px">Conozca más sobre nuestro sistema: <a href="#" style="color:#5571b3; text-decoration:underline">link del video</a></p>-->
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; margin:0 0 30px">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />
                                                    <!--  <a href="#" style="color:#5571b3; text-decoration:underline">Ayuda y soporte</a>--></p></td>
                    <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
                </tr>
            </table></td>
    </tr>
    <tr>
       <td style="font-size:0; line-height:0; padding:0"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
    </tr>
</table>

