<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td valign="top">
                    	<h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; margin:27px 0 14px">Tienes un nuevo vale que aprobar!</h1>
                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; margin:0 0 15px"><a href="<?php echo $this->url; ?>"><?php echo $this->url; ?></a></p>

                        </td>
                    <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

