<style type="text/css">



    body{margin:0; font-size:75%; line-height:1.42857; color:#626262; font-family:Arial,Helvetica,sans-serif; }

    p{
        font-size: 12px;
        line-height: 120%;
        margin: 0 0 13px;
        font-family: Arial, Helvetica, sans-serif;
        color: #505050;
    }




</style>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/header_correo-01.png" width="800" height="31" alt="Temaplate" /></td>
    </tr>
    <tr>
        <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr> <br>
                <td valign="top">
                    <h1 style="font-size:20px; line-height:20px; font-family:Arial, Helvetica, sans-serif; color:#008BD2; ">¡Felicidades tu vale ha sido canjeado!</h1>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#6d6c6c; line-height:14px; ">Esperamos que hayas disfrutado tu compra.</p>
                    <div style="  width: 470px;
  /* float: left; */
  height: 365px;">
                          <div style="  width: 440px;height: 350px;background-color: #008BD2;padding: 15px;">
                                     <div style="  width: 77px;
  height: 105px;
  padding: 0px 0px 0px 180px;
  text-align: center;
  color: #FFFFFF;">
                                  <div>
                                      <?php if(!empty($this->reserva['tienda_logo'])) $cadUrl= Cit_Server::getStatic()->host."imagenes/empresas/".$this->reserva['tienda_id']."/logo/".$this->reserva['tienda_logo']; else $cadUrl=Cit_Server::getContent()->host."img/tuerca.png";?>
                                      <img  src="<?php echo $cadUrl; ?>"   style="width:75px;height:75px">
                                  </div> 
                                  <div style="text-center"><span><?php echo $this->reserva['tienda_nombre']; ?></span></div>
                          </div>
                              <div style="border: 2px dotted #FFFFFF;width: 436px;height: 230px;">
                           
                                  <div style="   width: 407px;
  min-height: 57px;
  font-size: 25px;
  padding: 10px 15px 0px 15px;
  line-height: 1;
  color: #ffffff;
  text-align: center;"> <span>Vale de</span><br><span style="font-size:50px"><?php echo $this->reserva['consumo_moneda'].$this->reserva['oferta_monto_consumo']; ?></span></div>
  
                                
  
                                  <div style="  font-size: 17px;
  width: 427px;
  padding: 0px 5px 5px 5px;
  color: #FFFFFF;
  text-align: center;" ><span>Consumo mínimo de</span> <span><?php echo $this->reserva['consumo_moneda'].$this->reserva['oferta_consumo_minimo']; ?></span></div>
  
                          
                                  <div style="  width: 400px;height:auto;text-align: center;  padding-left: 35px;"> <div style="width: 343px;height: 35px;background: #F4B61C;padding: 10px 10px 10px 10px;font-size: 25px;font-weight: bold;color: #FFFFFF;border-radius: 10px;">
        <span >CANJEADO</span>
       
                                      </div></div>
  
  
                   <div style="  text-align: right;    width: 395px;height: 34px;font-size: 25px;
                                 color:#FFFFFF"><div><span>
                               <?php echo $this->reserva['oferta_puntos']; ?> puntos</span></div></div>
                    </div> 
                </div>
                         
                
            </div>
               
             
                    <div class="other">       

                        <p style="font-family:Arial, Helvetica, sans-serif; font-size:11px; line-height:14px; color:#6d6c6c; ">Atte:<br />
                            Equipo de Valeplaza<br />
                            <a href="#" style="color:#5571b3; text-decoration:underline">www.valeplaza.com</a><br />          

                    </div>
                <td width="162" style="font-size:0; line-height:0; padding:0"><img src="<?php echo Cit_Server::getContent()->host ?>img/iconaso_correo-01.png" width="162" height="163" alt="Template" /></td>
    </tr>
</table></td>
</tr>
<tr>
    <td style="font-size:0; line-height:0; padding:0 ;"><a href="http://ayuda.valeplaza.com/"><img src="<?php echo Cit_Server::getContent()->host ?>img/footer_correo-01.png" width="800" height="25" alt="Template" /></a></td>
</tr>
</table>