<!--Responsive navigation button-->
<!--<div class="resBtn">
    <a href="#"><span class="icon16 minia-icon-list-3"></span></a>
</div>

<div id="sidebarbg"></div>

<div id="sidebar">
    
    <div class="sidenav">
        <div class="sidebar-widget" style="margin: -1px 0 0 0;">
            <h5 class="title" style="margin-bottom:0">Navigation</h5>
        </div><!-- End .sidenav-widget 
        <div class="mainnav">
            <ul>
                <?php  //if(!empty($this->recursos)): ?>
                    <?php //foreach($this->recursos  as $recurso): ?>
                        <li>
                            <a href="<?php //if(!empty($recurso['rec_uri'])): echo '/'. str_replace(':','/',$recurso['rec_uri']); else: echo '#'; endif; ?>">
                                <span class="icon16 icomoon-icon-grid"></span><?php //echo $recurso['rec_nombre']; ?></a>
                            <?php  //if(!empty($recurso['subcategoria'])): ?>
                                <ul class="sub">
                                    <?php //foreach($recurso['subcategoria']  as $recurso): ?>
                                    <li><a href="<?php //echo '/'. str_replace(':','/',$recurso['rec_uri']); ?>"><span class="icon16 icomoon-icon-file"></span><?php //echo $recurso['rec_nombre']; ?></a></li>
                                    <?php //endforeach; ?>
                                </ul>
                            <?php //endif; ?>
                        </li>
                    <?php //endforeach; ?>
                <?php //endif; ?>
            </ul>
        </div>
    </div>
    
</div>-->