<!DOCTYPE html>
<html lang="es" prefix="og: http://ogp.me/ns#">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Cache-control" content="no-cache">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="red social, Mercaderos, red social mercaderos, la red para vender" name="keywords">
        <meta content="Mercaderos" name="author">
        <meta content="La primera red social comercial" name="description">
        <link type="image/x-icon" href="<?php echo Cit_Server::getContent()->host; ?>img/favicon.ico" rel="shortcut icon">
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">       
        <?php echo $this->headTitle('Mercaderos')->setSeparator('-');?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->render('head.phtml'); ?>
    </head>

    <body>
        <div id="bloquea" class="cargando" style="display: none">
                <img src="<?php echo Cit_Server::getContent()->host; ?>img/ico_loading.gif" style="margin: 220px auto !important;">
        </div>
        <script>
            og={};
            og.uriBase = '<?php echo Cit_Server::getContent()->host ?>';
            $(document).ready(function() {
            bootbox.setDefaults({
                    locale: "es"
                });
            })
        </script>
        <!-- loading animation -->
        <?php echo $this->render('header.phtml'); ?>
        <div id="content">
            
        <?php echo $this->layout()->content ?>
        
        </div>
        <?php   
            echo $this->render('footer.phtml');
        ?>
    </body>
</html>

