<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="red social, valeplaza, red social valeplaza, la red social donde ganas ahorrando" name="keywords">
        <meta content="valeplaza" name="author">
        <meta content="La primera red social comercial" name="description">
        <link type="image/x-icon" href="<?php echo Cit_Server::getContent()->host; ?>img/favicon.ico" rel="shortcut icon">
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">       
        <?php echo $this->headTitle('Valeplaza')->setSeparator('-');?>
        <?php echo $this->headMeta(); ?> 
        <!--<meta name="author" content="SuggeElson" />
        <meta name="description" content="Supr admin template - new premium responsive admin template. This template is designed to help you build the site administration without losing valuable time.Template contains all the important functions which must have one backend system.Build on great twitter boostrap framework" />
        <meta name="keywords" content="admin, admin template, admin theme, responsive, responsive admin, responsive admin template, responsive theme, themeforest, 960 grid system, grid, grid theme, liquid, masonry, jquery, administration, administration template, administration theme, mobile, touch , responsive layout, boostrap, twitter boostrap" />
        <meta name="application-name" content="Supr admin template" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />-->
        <?php echo $this->render('head.phtml') ?>
       
    </head>

    <body>
        <script>
            og={};
            og.uriBase = '<?php echo Cit_Server::getContent()->host ?>';
        </script>
        <!-- loading animation -->
        <?php echo $this->render('header.phtml') ?>
        <div id="content">
            
            <?php //echo $this->render('adm-sidebar.phtml') ?>
            <?php echo $this->layout()->content ?>
            
        </div>


        <?php if( !Zend_Registry::get('Susuario')->status) : echo $this->render('footer.phtml'); endif; ?>
    </body>
</html>

