<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Supr admin</title>
        <meta name="author" content="SuggeElson" />
        <meta name="description" content="Supr admin template - new premium responsive admin template. This template is designed to help you build the site administration without losing valuable time.Template contains all the important functions which must have one backend system.Build on great twitter boostrap framework" />
        <meta name="keywords" content="admin, admin template, admin theme, responsive, responsive admin, responsive admin template, responsive theme, themeforest, 960 grid system, grid, grid theme, liquid, masonry, jquery, administration, administration template, administration theme, mobile, touch , responsive layout, boostrap, twitter boostrap" />
        <meta name="application-name" content="Supr admin template" />
        <!-- Mobile Specific Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->render('head.phtml') ?>
    </head>

    <body>
        <script>
            og={};
            og.uriBase = '<?php echo Cit_Server::getStatic()->host ?>';
        </script>
        <!-- loading animation -->
        <div id="qLoverlay"></div>
        <div id="qLbar"></div>
        <?php echo $this->render('header.phtml') ?>
        <div id="wrapper">
            <?php echo $this->render('adm-sidebar.phtml') ?>
            <?php echo $this->layout()->content ?>
        </div>
        <?php echo $this->render('footer.phtml') ?>
    </body>
</html>

